In [13]:
import json
import requests

class Token:

    def __init__(self, file_data):
        self.URL = 'https://api.invertironline.com/token'
        self.Host = 'api.invertironline.com'
        self.ContentType = 'application/x-www-form-urlencoded'
        self.granttype = 'password'
        self.file_data = file_data

        with open(self.file_data) as json_file:
            self.user_data = json.load(json_file)

        self.data = {
            'Host': self.Host,
            'username': self.user_data[0]['username'],
            'password': self.user_data[0]['password'],
            'grant_type': self.granttype
        }

        self.headers = {'Content-Type': self.ContentType}

    def get_token(self):
        r = requests.post(url=self.URL, data=self.data, headers=self.headers)
        data = r.json()

        if 'error' in data.keys():
            print('Error found: ' + data['error'])
        else:
            print('Access Token: ' + data['access_token'])
            print('Refresh Token: ' + data['refresh_token'])
            print('Expires: ' + data['.expires'])

# Uso de la clase Token
if __name__ == '__main__':
    token_obj = Token('user_data.json')
    token_obj.get_token()

Access Token: eyJhbGciOiJSUzI1NiIsInR5cCI6ImF0K2p3dCJ9.eyJzdWIiOiI2NDk1MjgiLCJJRCI6IjY0OTUyOCIsImp0aSI6ImY4NmEzM2ZhLTNlMzAtNGRlZi1iMDhmLTc1OTk2MzNmODhhZiIsImNvbnN1bWVyX3R5cGUiOiIxIiwidGllbmVfY3VlbnRhIjoiVHJ1ZSIsInRpZW5lX3Byb2R1Y3RvX2J1cnNhdGlsIjoiVHJ1ZSIsInRpZW5lX3Byb2R1Y3RvX2FwaSI6IlRydWUiLCJ0aWVuZV9UeUMiOiJUcnVlIiwibmJmIjoxNzE3NjI4ODI4LCJleHAiOjE3MTc2Mjk3MjgsImlhdCI6MTcxNzYyODgyOCwiaXNzIjoiSU9MT2F1dGhTZXJ2ZXIiLCJhdWQiOiJJT0xPYXV0aFNlcnZlciJ9.I45B-jq3Rw59AmLz_sib59mKzVk0d7-cKQdN8zeSpFSG_QgzON7QyUJZeGh6fg-CfqE0yyFzOIxm7x6e0oUx6RVaAC9bTAk3WK7PIbylJaLomT4M1VVTa-mVzIZA-A3AXbe9X0Vo-Kn1Zxu431zwOf_uRK5j9VY3O4P6j2_-qj3QQlT57gEfTO6lgqXyc-s3vTNx8Wx7QDgobA36vlrI-5l4DiPEoZ0mwrvGHZaG5zraw-oHTsuAL7gF3Ot1UFVGm2Y35Y8RPbifzFuTcGmcNsi6WKOTBt4msquQ3cQsXTCq2oabrG0nvO98H1XFuhhTtURkkxcbQXauAPVDdpULcQ
Refresh Token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDk1MjgiLCJqdGkiOiJkOGFlZmJkNC04Nzc0LTRjY2ItODc2ZC03NDM2MDA5MjJkZjIiLCJydF9mYW1pbHkiOiIzOTkwZDQwOC04MDE5LTRjYzAtOWRjMi03YWJmYTA3NmMxZmYiLCJuYmYiOjE3MTc2Mjg4MjgsImV4cCI6MTcxNzYzMDAyOCwiaWF0IjoxNzE3NjI4ODI4LCJpc3MiOiJJT0xPYXV0aFNlcnZlciIsImF1ZCI6IklPTE9hdXRoU2VydmVyIn0.MUp5AxwFO5T-aYm8bcNbX_eY_b2hz5R5wa2SbY1tcW5gRKQOy3wAjmYVrO11eyp7XHlkhScYWa-aEeERe05ANq_RHA-d5w6H1jNpLcYid1C1wos46_hC3ABQQDYlXgFi9pQedCwTVUuqSjyxOrZcMW2pG7NlsDIH-8dzTD8N7F8227obG7Bnuc4XCVPq15GiETcau7HUn1TEfNrk40iKPSr1P7qpdKrSTTqV2l0rMbvCkhIG3e5R0nfuttWcX0yxnHtlTMkmJ7NRPxOhMhKOiPSV9Py4-NrQ91xDbKfYCXsLEWNSrZWHU6rFxH2AfY_jONK8SSnxyBgtgZUReAkwjQ
Expires: Wed, 05 Jun 2024 23:22:08 GMT

In [3]:
import json
import requests
from datetime import datetime, timedelta

class TokenManager:

    def __init__(self, file_data):
        self.file_data = file_data
        self.token_info = None
        self.load_user_data()
        self.token_url = 'https://api.invertironline.com/token'
        self.portfolio_url = 'https://api.invertironline.com/api/v2/portafolio'

    def load_user_data(self):
        with open(self.file_data) as json_file:
            self.user_data = json.load(json_file)
            self.username = self.user_data[0]['username']
            self.password = self.user_data[0]['password']

    def get_new_token(self):
        data = {
            'grant_type': 'password',
            'username': self.username,
            'password': self.password
        }
        headers = {'Content-Type': 'application/x-www-form-urlencoded'}
        response = requests.post(self.token_url, data=data, headers=headers)
        self.token_info = response.json()
        if 'error' in self.token_info:
            raise Exception(f"Error obtaining token: {self.token_info['error']}")
        self.token_info['expires_at'] = datetime.now() + timedelta(seconds=self.token_info['expires_in'])
    
    def refresh_token(self):
        data = {
            'grant_type': 'refresh_token',
            'refresh_token': self.token_info['refresh_token']
        }
        headers = {'Content-Type': 'application/x-www-form-urlencoded'}
        response = requests.post(self.token_url, data=data, headers=headers)
        new_token_info = response.json()
        if 'error' in new_token_info:
            raise Exception(f"Error refreshing token: {new_token_info['error']}")
        self.token_info.update(new_token_info)
        self.token_info['expires_at'] = datetime.now() + timedelta(seconds=self.token_info['expires_in'])

    def ensure_token(self):
        if not self.token_info or datetime.now() >= self.token_info['expires_at']:
            self.refresh_token() if self.token_info else self.get_new_token()

    def get_portfolio(self):
        self.ensure_token()
        headers = {'Authorization': f"Bearer {self.token_info['access_token']}"}
        response = requests.get(self.portfolio_url, headers=headers)
        if response.status_code != 200:
            raise Exception(f"Error fetching portfolio: {response.text}")
        return response.json()

if __name__ == '__main__':
    token_manager = TokenManager('user_data.json')
    portfolio = token_manager.get_portfolio()
    print(json.dumps(portfolio, indent=2))

{
  "pais": "argentina",
  "activos": [
    {
      "cantidad": 4.0,
      "comprometido": 0.0,
      "puntosVariacion": 0.0,
      "variacionDiaria": 0.42,
      "ultimoPrecio": 12832.0,
      "ppc": 5832.5,
      "gananciaPorcentaje": 120.0,
      "gananciaDinero": 27998.0,
      "valorizado": 51328.0,
      "titulo": {
        "simbolo": "AAPL",
        "descripcion": "Apple",
        "pais": "argentina",
        "mercado": "bcba",
        "tipo": "CEDEARS",
        "plazo": "t1",
        "moneda": "peso_Argentino"
      },
      "parking": null
    },
    {
      "cantidad": 555.0,
      "comprometido": 0.0,
      "puntosVariacion": 0.0,
      "variacionDiaria": -1.49,
      "ultimoPrecio": 67170.0,
      "ppc": 40964.09,
      "gananciaPorcentaje": 63.97,
      "gananciaDinero": 145442.8,
      "valorizado": 372793.5,
      "titulo": {
        "simbolo": "AL30",
        "descripcion": "Bono Rep. Argentina Usd Step Up 2030",
        "pais": "argentina",
        "mercado": "bcba",
        "tipo": "TitulosPublicos",
        "plazo": "t1",
        "moneda": "peso_Argentino"
      },
      "parking": null
    },
    {
      "cantidad": 30.0,
      "comprometido": 0.0,
      "puntosVariacion": 0.0,
      "variacionDiaria": -0.87,
      "ultimoPrecio": 965.5,
      "ppc": 597.717,
      "gananciaPorcentaje": 61.53,
      "gananciaDinero": 11033.5,
      "valorizado": 28965.0,
      "titulo": {
        "simbolo": "ALUA",
        "descripcion": "Aluar",
        "pais": "argentina",
        "mercado": "bcba",
        "tipo": "ACCIONES",
        "plazo": "t1",
        "moneda": "peso_Argentino"
      },
      "parking": null
    },
    {
      "cantidad": 14.0,
      "comprometido": 0.0,
      "puntosVariacion": 0.0,
      "variacionDiaria": 1.09,
      "ultimoPrecio": 1657.0,
      "ppc": 699.0,
      "gananciaPorcentaje": 137.05,
      "gananciaDinero": 13412.0,
      "valorizado": 23198.0,
      "titulo": {
        "simbolo": "AMZN",
        "descripcion": "Amazon",
        "pais": "argentina",
        "mercado": "bcba",
        "tipo": "CEDEARS",
        "plazo": "t1",
        "moneda": "peso_Argentino"
      },
      "parking": null
    },
    {
      "cantidad": 10.0,
      "comprometido": 0.0,
      "puntosVariacion": 0.0,
      "variacionDiaria": -2.21,
      "ultimoPrecio": 7877.15,
      "ppc": 1534.1,
      "gananciaPorcentaje": 413.47,
      "gananciaDinero": 63430.5,
      "valorizado": 78771.5,
      "titulo": {
        "simbolo": "BMA",
        "descripcion": "Banco Macro",
        "pais": "argentina",
        "mercado": "bcba",
        "tipo": "ACCIONES",
        "plazo": "t1",
        "moneda": "peso_Argentino"
      },
      "parking": null
    },
    {
      "cantidad": 38.0,
      "comprometido": 0.0,
      "puntosVariacion": 0.0,
      "variacionDiaria": 0.18,
      "ultimoPrecio": 115500.0,
      "ppc": 0.0,
      "gananciaPorcentaje": 0.0,
      "gananciaDinero": 0.0,
      "valorizado": 43890.0,
      "titulo": {
        "simbolo": "BPOA7",
        "descripcion": "Bopreal Serie 1A Vto. 31/10/27",
        "pais": "argentina",
        "mercado": "bcba",
        "tipo": "TitulosPublicos",
        "plazo": "t1",
        "moneda": "peso_Argentino"
      },
      "parking": null
    },
    {
      "cantidad": 38.0,
      "comprometido": 0.0,
      "puntosVariacion": 0.0,
      "variacionDiaria": -0.8,
      "ultimoPrecio": 103000.0,
      "ppc": 0.0,
      "gananciaPorcentaje": 0.0,
      "gananciaDinero": 0.0,
      "valorizado": 39140.0,
      "titulo": {
        "simbolo": "BPOB7",
        "descripcion": "Bopreal Serie 1B Vto. 31/10/27",
        "pais": "argentina",
        "mercado": "bcba",
        "tipo": "TitulosPublicos",
        "plazo": "t1",
        "moneda": "peso_Argentino"
      },
      "parking": null
    },
    {
      "cantidad": 176.0,
      "comprometido": 0.0,
      "puntosVariacion": 0.0,
      "variacionDiaria": -0.55,
      "ultimoPrecio": 91000.0,
      "ppc": 92857.159,
      "gananciaPorcentaje": -2.0,
      "gananciaDinero": -3268.6,
      "valorizado": 160160.0,
      "titulo": {
        "simbolo": "BPOD7",
        "descripcion": "Bopreal Serie 1D Vto. 31/10/27",
        "pais": "argentina",
        "mercado": "bcba",
        "tipo": "TitulosPublicos",
        "plazo": "t1",
        "moneda": "peso_Argentino"
      },
      "parking": null
    },
    {
      "cantidad": 100.0,
      "comprometido": 0.0,
      "puntosVariacion": 0.0,
      "variacionDiaria": -0.79,
      "ultimoPrecio": 99200.0,
      "ppc": 90000.0,
      "gananciaPorcentaje": 10.22,
      "gananciaDinero": 9200.0,
      "valorizado": 99200.0,
      "titulo": {
        "simbolo": "BPY26",
        "descripcion": "Bopreal Serie 3 Vto 31/05/26",
        "pais": "argentina",
        "mercado": "bcba",
        "tipo": "TitulosPublicos",
        "plazo": "t1",
        "moneda": "peso_Argentino"
      },
      "parking": null
    },
    {
      "cantidad": 1.0,
      "comprometido": 0.0,
      "puntosVariacion": 0.0,
      "variacionDiaria": 0.01,
      "ultimoPrecio": 24427.0,
      "ppc": 13158.0,
      "gananciaPorcentaje": 85.64,
      "gananciaDinero": 11269.0,
      "valorizado": 24427.0,
      "titulo": {
        "simbolo": "BRKB",
        "descripcion": "Berkshire Hathaway",
        "pais": "argentina",
        "mercado": "bcba",
        "tipo": "CEDEARS",
        "plazo": "t1",
        "moneda": "peso_Argentino"
      },
      "parking": null
    },
    {
      "cantidad": 2.0,
      "comprometido": 0.0,
      "puntosVariacion": 0.0,
      "variacionDiaria": 0.84,
      "ultimoPrecio": 26974.0,
      "ppc": 9033.0,
      "gananciaPorcentaje": 198.61,
      "gananciaDinero": 35882.0,
      "valorizado": 53948.0,
      "titulo": {
        "simbolo": "C",
        "descripcion": "Citigroup",
        "pais": "argentina",
        "mercado": "bcba",
        "tipo": "CEDEARS",
        "plazo": "t1",
        "moneda": "peso_Argentino"
      },
      "parking": null
    },
    {
      "cantidad": 68.0,
      "comprometido": 0.0,
      "puntosVariacion": 0.0,
      "variacionDiaria": -1.13,
      "ultimoPrecio": 1168.0,
      "ppc": 495.89,
      "gananciaPorcentaje": 135.53,
      "gananciaDinero": 45703.5,
      "valorizado": 79424.0,
      "titulo": {
        "simbolo": "CEPU",
        "descripcion": "Central Puerto Sa",
        "pais": "argentina",
        "mercado": "bcba",
        "tipo": "ACCIONES",
        "plazo": "t1",
        "moneda": "peso_Argentino"
      },
      "parking": null
    },
    {
      "cantidad": 583.548,
      "comprometido": 0.0,
      "puntosVariacion": 94.29439,
      "variacionDiaria": -0.2,
      "ultimoPrecio": 94.29439,
      "ppc": 25.705,
      "gananciaPorcentaje": 266.83,
      "gananciaDinero": 40025.31,
      "valorizado": 55025.30269572,
      "titulo": {
        "simbolo": "CONIOLA",
        "descripcion": "Adcap Acciones",
        "pais": "argentina",
        "mercado": "bcba",
        "tipo": "FondoComundeInversion",
        "plazo": "t1",
        "moneda": "peso_Argentino"
      },
      "parking": null
    },
    {
      "cantidad": 255.766,
      "comprometido": 0.0,
      "puntosVariacion": 100.726238,
      "variacionDiaria": 0.12,
      "ultimoPrecio": 100.726238,
      "ppc": 39.098,
      "gananciaPorcentaje": 157.62,
      "gananciaDinero": 15762.35,
      "valorizado": 25762.346988308,
      "titulo": {
        "simbolo": "CRTAFAA",
        "descripcion": "Adcap Renta Fija",
        "pais": "argentina",
        "mercado": "bcba",
        "tipo": "FondoComundeInversion",
        "plazo": "t2",
        "moneda": "peso_Argentino"
      },
      "parking": null
    },
    {
      "cantidad": 108.0,
      "comprometido": 0.0,
      "puntosVariacion": 0.0,
      "variacionDiaria": -1.07,
      "ultimoPrecio": 55300.0,
      "ppc": 48282.778,
      "gananciaPorcentaje": 14.53,
      "gananciaDinero": 7578.6,
      "valorizado": 59724.0,
      "titulo": {
        "simbolo": "GD35",
        "descripcion": "Bonos Rep. Arg. U$S Step Up V.09/07/35",
        "pais": "argentina",
        "mercado": "bcba",
        "tipo": "TitulosPublicos",
        "plazo": "t1",
        "moneda": "peso_Argentino"
      },
      "parking": null
    },
    {
      "cantidad": 76.0,
      "comprometido": 0.0,
      "puntosVariacion": 0.0,
      "variacionDiaria": -0.9,
      "ultimoPrecio": 4269.0,
      "ppc": 1615.991,
      "gananciaPorcentaje": 164.17,
      "gananciaDinero": 201628.7,
      "valorizado": 324444.0,
      "titulo": {
        "simbolo": "GGAL",
        "descripcion": "Grupo Financiero Galicia S.A",
        "pais": "argentina",
        "mercado": "bcba",
        "tipo": "ACCIONES",
        "plazo": "t1",
        "moneda": "peso_Argentino"
      },
      "parking": null
    },
    {
      "cantidad": 11.0,
      "comprometido": 0.0,
      "puntosVariacion": 0.0,
      "variacionDiaria": 1.03,
      "ultimoPrecio": 3970.0,
      "ppc": 1543.318,
      "gananciaPorcentaje": 157.23,
      "gananciaDinero": 26693.5,
      "valorizado": 43670.0,
      "titulo": {
        "simbolo": "GOOGL",
        "descripcion": "Google",
        "pais": "argentina",
        "mercado": "bcba",
        "tipo": "CEDEARS",
        "plazo": "t1",
        "moneda": "peso_Argentino"
      },
      "parking": null
    },
    {
      "cantidad": 3.0,
      "comprometido": 0.0,
      "puntosVariacion": 0.0,
      "variacionDiaria": -1.31,
      "ultimoPrecio": 17236.0,
      "ppc": 6122.333,
      "gananciaPorcentaje": 181.52,
      "gananciaDinero": 33341.0,
      "valorizado": 51708.0,
      "titulo": {
        "simbolo": "JPM",
        "descripcion": "Jpmorgan Chase & Co.",
        "pais": "argentina",
        "mercado": "bcba",
        "tipo": "CEDEARS",
        "plazo": "t1",
        "moneda": "peso_Argentino"
      },
      "parking": null
    },
    {
      "cantidad": 4.0,
      "comprometido": 0.0,
      "puntosVariacion": 0.0,
      "variacionDiaria": -2.01,
      "ultimoPrecio": 17506.0,
      "ppc": 6350.0,
      "gananciaPorcentaje": 175.68,
      "gananciaDinero": 44624.0,
      "valorizado": 70024.0,
      "titulo": {
        "simbolo": "MELI",
        "descripcion": "Mercadolibre",
        "pais": "argentina",
        "mercado": "bcba",
        "tipo": "CEDEARS",
        "plazo": "t1",
        "moneda": "peso_Argentino"
      },
      "parking": null
    },
    {
      "cantidad": 2.0,
      "comprometido": 0.0,
      "puntosVariacion": 0.0,
      "variacionDiaria": 1.52,
      "ultimoPrecio": 18470.0,
      "ppc": 8892.0,
      "gananciaPorcentaje": 107.71,
      "gananciaDinero": 19156.0,
      "valorizado": 36940.0,
      "titulo": {
        "simbolo": "MSFT",
        "descripcion": "Microsoft",
        "pais": "argentina",
        "mercado": "bcba",
        "tipo": "CEDEARS",
        "plazo": "t1",
        "moneda": "peso_Argentino"
      },
      "parking": null
    },
    {
      "cantidad": 42.0,
      "comprometido": 0.0,
      "puntosVariacion": 0.0,
      "variacionDiaria": -0.22,
      "ultimoPrecio": 2327.0,
      "ppc": 1059.524,
      "gananciaPorcentaje": 119.62,
      "gananciaDinero": 53234.0,
      "valorizado": 97734.0,
      "titulo": {
        "simbolo": "PAMP",
        "descripcion": "Pampa Energ\u00eda",
        "pais": "argentina",
        "mercado": "bcba",
        "tipo": "ACCIONES",
        "plazo": "t1",
        "moneda": "peso_Argentino"
      },
      "parking": null
    },
    {
      "cantidad": 3.0,
      "comprometido": 0.0,
      "puntosVariacion": 0.0,
      "variacionDiaria": 1.81,
      "ultimoPrecio": 30384.5,
      "ppc": 8784.5,
      "gananciaPorcentaje": 245.88,
      "gananciaDinero": 64800.0,
      "valorizado": 91153.5,
      "titulo": {
        "simbolo": "QQQ",
        "descripcion": "Etf Invesco Qqq Trust",
        "pais": "argentina",
        "mercado": "bcba",
        "tipo": "CEDEARS",
        "plazo": "t1",
        "moneda": "peso_Argentino"
      },
      "parking": null
    },
    {
      "cantidad": 7.0,
      "comprometido": 0.0,
      "puntosVariacion": 0.0,
      "variacionDiaria": 0.98,
      "ultimoPrecio": 34999.5,
      "ppc": 19946.571,
      "gananciaPorcentaje": 75.46,
      "gananciaDinero": 105370.5,
      "valorizado": 244996.5,
      "titulo": {
        "simbolo": "SPY",
        "descripcion": "Etf Spdr S&P 500",
        "pais": "argentina",
        "mercado": "bcba",
        "tipo": "CEDEARS",
        "plazo": "t1",
        "moneda": "peso_Argentino"
      },
      "parking": null
    },
    {
      "cantidad": 7.0,
      "comprometido": 0.0,
      "puntosVariacion": 0.0,
      "variacionDiaria": -0.07,
      "ultimoPrecio": 4665.0,
      "ppc": 1267.814,
      "gananciaPorcentaje": 267.95,
      "gananciaDinero": 23780.3,
      "valorizado": 32655.0,
      "titulo": {
        "simbolo": "TGSU2",
        "descripcion": "Transportadora Gas Del Sur",
        "pais": "argentina",
        "mercado": "bcba",
        "tipo": "ACCIONES",
        "plazo": "t1",
        "moneda": "peso_Argentino"
      },
      "parking": null
    },
    {
      "cantidad": 5613.0,
      "comprometido": 0.0,
      "puntosVariacion": 0.0,
      "variacionDiaria": 0.34,
      "ultimoPrecio": 1756.0,
      "ppc": 1750.0,
      "gananciaPorcentaje": 0.34,
      "gananciaDinero": 336.78,
      "valorizado": 98564.28,
      "titulo": {
        "simbolo": "TX26",
        "descripcion": "Bono Del Tesoro Boncer 2% $ 2026",
        "pais": "argentina",
        "mercado": "bcba",
        "tipo": "TitulosPublicos",
        "plazo": "t1",
        "moneda": "peso_Argentino"
      },
      "parking": null
    },
    {
      "cantidad": 48.0,
      "comprometido": 0.0,
      "puntosVariacion": 0.0,
      "variacionDiaria": -1.06,
      "ultimoPrecio": 973.0,
      "ppc": 813.0,
      "gananciaPorcentaje": 19.68,
      "gananciaDinero": 7680.0,
      "valorizado": 46704.0,
      "titulo": {
        "simbolo": "TXAR",
        "descripcion": "Ternium Argentina Sa",
        "pais": "argentina",
        "mercado": "bcba",
        "tipo": "ACCIONES",
        "plazo": "t1",
        "moneda": "peso_Argentino"
      },
      "parking": null
    },
    {
      "cantidad": 15.0,
      "comprometido": 0.0,
      "puntosVariacion": 0.0,
      "variacionDiaria": -0.73,
      "ultimoPrecio": 18617.0,
      "ppc": 3909.167,
      "gananciaPorcentaje": 376.23,
      "gananciaDinero": 220617.5,
      "valorizado": 279255.0,
      "titulo": {
        "simbolo": "VIST",
        "descripcion": "Vista Energy S.A.B. De C.V.",
        "pais": "argentina",
        "mercado": "bcba",
        "tipo": "CEDEARS",
        "plazo": "t1",
        "moneda": "peso_Argentino"
      },
      "parking": null
    },
    {
      "cantidad": 15.0,
      "comprometido": 0.0,
      "puntosVariacion": 0.0,
      "variacionDiaria": 1.55,
      "ultimoPrecio": 27156.0,
      "ppc": 12303.427,
      "gananciaPorcentaje": 120.71,
      "gananciaDinero": 222788.6,
      "valorizado": 407340.0,
      "titulo": {
        "simbolo": "YPFD",
        "descripcion": "Ypf",
        "pais": "argentina",
        "mercado": "bcba",
        "tipo": "ACCIONES",
        "plazo": "t1",
        "moneda": "peso_Argentino"
      },
      "parking": null
    }
  ]
}

In [43]:
data={
        "username": "Fedebohl",
        "password": "Fedecapo_01"
    }
data['username']

'Fedebohl'

In [38]:
import requests
from datetime import datetime, timedelta
import pandas as pd

class TokenManager:
    def __init__(self, username,password):
        self.token_info = None
        self.user_data={
                        'username':username,
                        'password':password
                        }
        self.load_user_data()
        self.token_url = 'https://api.invertironline.com/token'
        self.base_url = 'https://api.invertironline.com/api/v2'
        self.portfolio_url = f'{self.base_url}/portafolio'
        self.quotes_url = f'{self.base_url}/Cotizaciones/{{instrument}}/{{country}}/Todos'

    def load_user_data(self):
        self.username = self.user_data['username']
        self.password = self.user_data['password']

    def get_new_token(self):
        data = {
            'grant_type': 'password',
            'username': self.username,
            'password': self.password
        }
        headers = {'Content-Type': 'application/x-www-form-urlencoded'}
        response = requests.post(self.token_url, data=data, headers=headers)
        self.token_info = response.json()
        if 'error' in self.token_info:
            raise Exception(f"Error obtaining token: {self.token_info['error']}")
        self.token_info['expires_at'] = datetime.now() + timedelta(seconds=self.token_info['expires_in'])
    
    def refresh_token(self):
        data = {
            'grant_type': 'refresh_token',
            'refresh_token': self.token_info['refresh_token']
        }
        headers = {'Content-Type': 'application/x-www-form-urlencoded'}
        response = requests.post(self.token_url, data=data, headers=headers)
        new_token_info = response.json()
        if 'error' in new_token_info:
            raise Exception(f"Error refreshing token: {new_token_info['error']}")
        self.token_info.update(new_token_info)
        self.token_info['expires_at'] = datetime.now() + timedelta(seconds=self.token_info['expires_in'])

    def ensure_token(self):
        if not self.token_info or datetime.now() >= self.token_info['expires_at']:
            self.refresh_token() if self.token_info else self.get_new_token()

    def get_portfolio(self):
        self.ensure_token()
        headers = {'Authorization': f"Bearer {self.token_info['access_token']}"}
        response = requests.get(self.portfolio_url, headers=headers)
        if response.status_code != 200:
            raise Exception(f"Error fetching portfolio: {response.text}")
        return response.json()

    def get_quotes(self, instrument, country):
        self.ensure_token()
        url = self.quotes_url.format(instrument=instrument, country=country)
        headers = {'Authorization': f"Bearer {self.token_info['access_token']}"}
        response = requests.get(url, headers=headers)
        if response.status_code != 200:
            raise Exception(f"Error fetching {instrument} quotes: {response.text}")
        df=pd.DataFrame(response.json()['titulos'])
        return df[['simbolo','ultimoPrecio']]

if __name__ == '__main__':
    token_manager = TokenManager('user_data.json')
    # Obtener cotizaciones de acciones
    df=token_manager.get_quotes('Acciones', 'argentina')
    df

In [40]:
token_manager.token_info

{'access_token': 'eyJhbGciOiJSUzI1NiIsInR5cCI6ImF0K2p3dCJ9.eyJzdWIiOiI2NDk1MjgiLCJJRCI6IjY0OTUyOCIsImp0aSI6ImE2ZTVlYmQ0LTA2MmItNDQyYS04M2RmLTMxOWQ5OGVlY2I4NiIsImNvbnN1bWVyX3R5cGUiOiIxIiwidGllbmVfY3VlbnRhIjoiVHJ1ZSIsInRpZW5lX3Byb2R1Y3RvX2J1cnNhdGlsIjoiVHJ1ZSIsInRpZW5lX3Byb2R1Y3RvX2FwaSI6IlRydWUiLCJ0aWVuZV9UeUMiOiJUcnVlIiwibmJmIjoxNzE3NjMwMzQxLCJleHAiOjE3MTc2MzEyNDEsImlhdCI6MTcxNzYzMDM0MSwiaXNzIjoiSU9MT2F1dGhTZXJ2ZXIiLCJhdWQiOiJJT0xPYXV0aFNlcnZlciJ9.ShPc4cEoEKskj286kcu4ytUH2VW_m-SAVIbaZlDx4A2whwT8h3L8jbAsuAkO8ag6di7TtQRHl9HbzcnvSHIQChN9mRco-YUKyfwc8dsKlkTH94EQq0otpiabOfH2MM2W6h7ezWSZbs2tyvBKxCWkFSQI4sr4IJvzUKUz3vSwH0L36DKiOKj_4WWP4_jO3QLE06lz1bYo7hbdVIMmNdwXxs9ZAR0C9VpXcfQMGmHZ6z2_DN8ecgDPYVqzluUzu1TnDQrZpYz6tBLzbU6GKmwIeHvuxv4YRhSuBj5lQU0vCa2Id5-Z86sBqKljSZop7ziuur3Zq2ZXN5eq8bA6gFjRVg',
 'token_type': 'bearer',
 'expires_in': 1200,
 'refresh_token': 'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDk1MjgiLCJqdGkiOiI2MGNkYzQwMi0yYmMwLTQyNmMtYTAyNi0wY2VlZjY0ZmI2YTkiLCJydF9mYW1pbHkiOiIzMmQ0MTdkMy0yYzc4LTRiYTAtYWYyZi01NzYwZGYwYzNlMjciLCJuYmYiOjE3MTc2MzAzNDEsImV4cCI6MTcxNzYzMTU0MSwiaWF0IjoxNzE3NjMwMzQxLCJpc3MiOiJJT0xPYXV0aFNlcnZlciIsImF1ZCI6IklPTE9hdXRoU2VydmVyIn0.HuiBD5wHYn9g0yplf0VvAdZe3nsTc52PEf6a4Kz3HPDVxsEi1Lg1Aw5C4ZjSSyFPtu7foUmJnS9K-sdoe9KJDrLQd7Jv_D3VSVK2a7_JUg_U5WgZ973Bw72tBEt5p16thFU1DoEVbSH_relJHVy23MSUDXQVAigw2bePM_qW7RmoV0nDnnJzKWrZ5B0RxhpFlqi7IZqk1WXtUZgrjgn4rj7KbTiOZmXY9LFB3Gam2inoQsXhaFU5DuiX93mOuihKppIBd7Irsj0nRfLMxG4et2WpF7bq7zVzk3vVyOUPfshXKKPswbHSxIIZFuKm2V49FR4YMGG9zYhtQJHuKepAKA',
 '.issued': 'Wed, 05 Jun 2024 23:32:21 GMT',
 '.expires': 'Wed, 05 Jun 2024 23:47:21 GMT',
 '.refreshexpires': 'Wed, 05 Jun 2024 23:52:21 GMT',
 'expires_at': datetime.datetime(2024, 6, 5, 20, 52, 21, 226050)}

In [41]:
token_manager.get_quotes('titulosPublicos', 'argentina')

    simbolo  ultimoPrecio
0      AE38      57430.00
1     AE38C         38.00
2     AE38D         45.30
3      AL29      69280.00
4     AL29C         46.30
..      ...           ...
146   TZXD5        141.25
147   TZXD6        130.75
148   TZXD7        118.50
149   TZXM5        111.00
150   TZXM6        111.80

[151 rows x 2 columns]

In [37]:
df[['simbolo','ultimoPrecio']]

    simbolo  ultimoPrecio
0       AAL       7620.00
1      AALD          5.99
2       AAP       6000.00
3      AAPL      12832.00
4     AAPLC         17.50
..      ...           ...
461     YYD          6.48
462    YZCA          0.00
463      ZM       1734.00
464     ZMC          6.15
465     ZMD          1.40

[466 rows x 2 columns]