In [13]:
import json
import requests

class Token:

    def __init__(self, file_data):
        self.URL = 'https://api.invertironline.com/token'
        self.Host = 'api.invertironline.com'
        self.ContentType = 'application/x-www-form-urlencoded'
        self.granttype = 'password'
        self.file_data = file_data

        with open(self.file_data) as json_file:
            self.user_data = json.load(json_file)

        self.data = {
            'Host': self.Host,
            'username': self.user_data[0]['username'],
            'password': self.user_data[0]['password'],
            'grant_type': self.granttype
        }

        self.headers = {'Content-Type': self.ContentType}

    def get_token(self):
        r = requests.post(url=self.URL, data=self.data, headers=self.headers)
        data = r.json()

        if 'error' in data.keys():
            print('Error found: ' + data['error'])
        else:
            print('Access Token: ' + data['access_token'])
            print('Refresh Token: ' + data['refresh_token'])
            print('Expires: ' + data['.expires'])

# Uso de la clase Token
if __name__ == '__main__':
    token_obj = Token('user_data.json')
    token_obj.get_token()

Access Token: eyJhbGciOiJSUzI1NiIsInR5cCI6ImF0K2p3dCJ9.eyJzdWIiOiI2NDk1MjgiLCJJRCI6IjY0OTUyOCIsImp0aSI6ImY4NmEzM2ZhLTNlMzAtNGRlZi1iMDhmLTc1OTk2MzNmODhhZiIsImNvbnN1bWVyX3R5cGUiOiIxIiwidGllbmVfY3VlbnRhIjoiVHJ1ZSIsInRpZW5lX3Byb2R1Y3RvX2J1cnNhdGlsIjoiVHJ1ZSIsInRpZW5lX3Byb2R1Y3RvX2FwaSI6IlRydWUiLCJ0aWVuZV9UeUMiOiJUcnVlIiwibmJmIjoxNzE3NjI4ODI4LCJleHAiOjE3MTc2Mjk3MjgsImlhdCI6MTcxNzYyODgyOCwiaXNzIjoiSU9MT2F1dGhTZXJ2ZXIiLCJhdWQiOiJJT0xPYXV0aFNlcnZlciJ9.I45B-jq3Rw59AmLz_sib59mKzVk0d7-cKQdN8zeSpFSG_QgzON7QyUJZeGh6fg-CfqE0yyFzOIxm7x6e0oUx6RVaAC9bTAk3WK7PIbylJaLomT4M1VVTa-mVzIZA-A3AXbe9X0Vo-Kn1Zxu431zwOf_uRK5j9VY3O4P6j2_-qj3QQlT57gEfTO6lgqXyc-s3vTNx8Wx7QDgobA36vlrI-5l4DiPEoZ0mwrvGHZaG5zraw-oHTsuAL7gF3Ot1UFVGm2Y35Y8RPbifzFuTcGmcNsi6WKOTBt4msquQ3cQsXTCq2oabrG0nvO98H1XFuhhTtURkkxcbQXauAPVDdpULcQ
Refresh Token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDk1MjgiLCJqdGkiOiJkOGFlZmJkNC04Nzc0LTRjY2ItODc2ZC03NDM2MDA5MjJkZjIiLCJydF9mYW1pbHkiOiIzOTkwZDQwOC04MDE5LTRjYzAtOWRjMi03YWJmYTA3NmMxZmYiLCJuYmYiOjE3MTc2Mjg4MjgsImV4cCI6MTcxNzYzMDAyOCwiaWF0IjoxNzE3NjI4ODI4LCJpc3MiOiJJT0xPYXV0aFNlcnZlciIsImF1ZCI6IklPTE9hdXRoU2VydmVyIn0.MUp5AxwFO5T-aYm8bcNbX_eY_b2hz5R5wa2SbY1tcW5gRKQOy3wAjmYVrO11eyp7XHlkhScYWa-aEeERe05ANq_RHA-d5w6H1jNpLcYid1C1wos46_hC3ABQQDYlXgFi9pQedCwTVUuqSjyxOrZcMW2pG7NlsDIH-8dzTD8N7F8227obG7Bnuc4XCVPq15GiETcau7HUn1TEfNrk40iKPSr1P7qpdKrSTTqV2l0rMbvCkhIG3e5R0nfuttWcX0yxnHtlTMkmJ7NRPxOhMhKOiPSV9Py4-NrQ91xDbKfYCXsLEWNSrZWHU6rFxH2AfY_jONK8SSnxyBgtgZUReAkwjQ
Expires: Wed, 05 Jun 2024 23:22:08 GMT

In [3]:
import json
import requests
from datetime import datetime, timedelta

class TokenManager:

    def __init__(self, file_data):
        self.file_data = file_data
        self.token_info = None
        self.load_user_data()
        self.token_url = 'https://api.invertironline.com/token'
        self.portfolio_url = 'https://api.invertironline.com/api/v2/portafolio'

    def load_user_data(self):
        with open(self.file_data) as json_file:
            self.user_data = json.load(json_file)
            self.username = self.user_data[0]['username']
            self.password = self.user_data[0]['password']

    def get_new_token(self):
        data = {
            'grant_type': 'password',
            'username': self.username,
            'password': self.password
        }
        headers = {'Content-Type': 'application/x-www-form-urlencoded'}
        response = requests.post(self.token_url, data=data, headers=headers)
        self.token_info = response.json()
        if 'error' in self.token_info:
            raise Exception(f"Error obtaining token: {self.token_info['error']}")
        self.token_info['expires_at'] = datetime.now() + timedelta(seconds=self.token_info['expires_in'])
    
    def refresh_token(self):
        data = {
            'grant_type': 'refresh_token',
            'refresh_token': self.token_info['refresh_token']
        }
        headers = {'Content-Type': 'application/x-www-form-urlencoded'}
        response = requests.post(self.token_url, data=data, headers=headers)
        new_token_info = response.json()
        if 'error' in new_token_info:
            raise Exception(f"Error refreshing token: {new_token_info['error']}")
        self.token_info.update(new_token_info)
        self.token_info['expires_at'] = datetime.now() + timedelta(seconds=self.token_info['expires_in'])

    def ensure_token(self):
        if not self.token_info or datetime.now() >= self.token_info['expires_at']:
            self.refresh_token() if self.token_info else self.get_new_token()

    def get_portfolio(self):
        self.ensure_token()
        headers = {'Authorization': f"Bearer {self.token_info['access_token']}"}
        response = requests.get(self.portfolio_url, headers=headers)
        if response.status_code != 200:
            raise Exception(f"Error fetching portfolio: {response.text}")
        return response.json()

if __name__ == '__main__':
    token_manager = TokenManager('user_data.json')
    portfolio = token_manager.get_portfolio()
    print(json.dumps(portfolio, indent=2))

{
  "pais": "argentina",
  "activos": [
    {
      "cantidad": 4.0,
      "comprometido": 0.0,
      "puntosVariacion": 0.0,
      "variacionDiaria": 0.42,
      "ultimoPrecio": 12832.0,
      "ppc": 5832.5,
      "gananciaPorcentaje": 120.0,
      "gananciaDinero": 27998.0,
      "valorizado": 51328.0,
      "titulo": {
        "simbolo": "AAPL",
        "descripcion": "Apple",
        "pais": "argentina",
        "mercado": "bcba",
        "tipo": "CEDEARS",
        "plazo": "t1",
        "moneda": "peso_Argentino"
      },
      "parking": null
    },
    {
      "cantidad": 555.0,
      "comprometido": 0.0,
      "puntosVariacion": 0.0,
      "variacionDiaria": -1.49,
      "ultimoPrecio": 67170.0,
      "ppc": 40964.09,
      "gananciaPorcentaje": 63.97,
      "gananciaDinero": 145442.8,
      "valorizado": 372793.5,
      "titulo": {
        "simbolo": "AL30",
        "descripcion": "Bono Rep. Argentina Usd Step Up 2030",
        "pais": "argentina",
        "mercado": "bcba",
        "tipo": "TitulosPublicos",
        "plazo": "t1",
        "moneda": "peso_Argentino"
      },
      "parking": null
    },
    {
      "cantidad": 30.0,
      "comprometido": 0.0,
      "puntosVariacion": 0.0,
      "variacionDiaria": -0.87,
      "ultimoPrecio": 965.5,
      "ppc": 597.717,
      "gananciaPorcentaje": 61.53,
      "gananciaDinero": 11033.5,
      "valorizado": 28965.0,
      "titulo": {
        "simbolo": "ALUA",
        "descripcion": "Aluar",
        "pais": "argentina",
        "mercado": "bcba",
        "tipo": "ACCIONES",
        "plazo": "t1",
        "moneda": "peso_Argentino"
      },
      "parking": null
    },
    {
      "cantidad": 14.0,
      "comprometido": 0.0,
      "puntosVariacion": 0.0,
      "variacionDiaria": 1.09,
      "ultimoPrecio": 1657.0,
      "ppc": 699.0,
      "gananciaPorcentaje": 137.05,
      "gananciaDinero": 13412.0,
      "valorizado": 23198.0,
      "titulo": {
        "simbolo": "AMZN",
        "descripcion": "Amazon",
        "pais": "argentina",
        "mercado": "bcba",
        "tipo": "CEDEARS",
        "plazo": "t1",
        "moneda": "peso_Argentino"
      },
      "parking": null
    },
    {
      "cantidad": 10.0,
      "comprometido": 0.0,
      "puntosVariacion": 0.0,
      "variacionDiaria": -2.21,
      "ultimoPrecio": 7877.15,
      "ppc": 1534.1,
      "gananciaPorcentaje": 413.47,
      "gananciaDinero": 63430.5,
      "valorizado": 78771.5,
      "titulo": {
        "simbolo": "BMA",
        "descripcion": "Banco Macro",
        "pais": "argentina",
        "mercado": "bcba",
        "tipo": "ACCIONES",
        "plazo": "t1",
        "moneda": "peso_Argentino"
      },
      "parking": null
    },
    {
      "cantidad": 38.0,
      "comprometido": 0.0,
      "puntosVariacion": 0.0,
      "variacionDiaria": 0.18,
      "ultimoPrecio": 115500.0,
      "ppc": 0.0,
      "gananciaPorcentaje": 0.0,
      "gananciaDinero": 0.0,
      "valorizado": 43890.0,
      "titulo": {
        "simbolo": "BPOA7",
        "descripcion": "Bopreal Serie 1A Vto. 31/10/27",
        "pais": "argentina",
        "mercado": "bcba",
        "tipo": "TitulosPublicos",
        "plazo": "t1",
        "moneda": "peso_Argentino"
      },
      "parking": null
    },
    {
      "cantidad": 38.0,
      "comprometido": 0.0,
      "puntosVariacion": 0.0,
      "variacionDiaria": -0.8,
      "ultimoPrecio": 103000.0,
      "ppc": 0.0,
      "gananciaPorcentaje": 0.0,
      "gananciaDinero": 0.0,
      "valorizado": 39140.0,
      "titulo": {
        "simbolo": "BPOB7",
        "descripcion": "Bopreal Serie 1B Vto. 31/10/27",
        "pais": "argentina",
        "mercado": "bcba",
        "tipo": "TitulosPublicos",
        "plazo": "t1",
        "moneda": "peso_Argentino"
      },
      "parking": null
    },
    {
      "cantidad": 176.0,
      "comprometido": 0.0,
      "puntosVariacion": 0.0,
      "variacionDiaria": -0.55,
      "ultimoPrecio": 91000.0,
      "ppc": 92857.159,
      "gananciaPorcentaje": -2.0,
      "gananciaDinero": -3268.6,
      "valorizado": 160160.0,
      "titulo": {
        "simbolo": "BPOD7",
        "descripcion": "Bopreal Serie 1D Vto. 31/10/27",
        "pais": "argentina",
        "mercado": "bcba",
        "tipo": "TitulosPublicos",
        "plazo": "t1",
        "moneda": "peso_Argentino"
      },
      "parking": null
    },
    {
      "cantidad": 100.0,
      "comprometido": 0.0,
      "puntosVariacion": 0.0,
      "variacionDiaria": -0.79,
      "ultimoPrecio": 99200.0,
      "ppc": 90000.0,
      "gananciaPorcentaje": 10.22,
      "gananciaDinero": 9200.0,
      "valorizado": 99200.0,
      "titulo": {
        "simbolo": "BPY26",
        "descripcion": "Bopreal Serie 3 Vto 31/05/26",
        "pais": "argentina",
        "mercado": "bcba",
        "tipo": "TitulosPublicos",
        "plazo": "t1",
        "moneda": "peso_Argentino"
      },
      "parking": null
    },
    {
      "cantidad": 1.0,
      "comprometido": 0.0,
      "puntosVariacion": 0.0,
      "variacionDiaria": 0.01,
      "ultimoPrecio": 24427.0,
      "ppc": 13158.0,
      "gananciaPorcentaje": 85.64,
      "gananciaDinero": 11269.0,
      "valorizado": 24427.0,
      "titulo": {
        "simbolo": "BRKB",
        "descripcion": "Berkshire Hathaway",
        "pais": "argentina",
        "mercado": "bcba",
        "tipo": "CEDEARS",
        "plazo": "t1",
        "moneda": "peso_Argentino"
      },
      "parking": null
    },
    {
      "cantidad": 2.0,
      "comprometido": 0.0,
      "puntosVariacion": 0.0,
      "variacionDiaria": 0.84,
      "ultimoPrecio": 26974.0,
      "ppc": 9033.0,
      "gananciaPorcentaje": 198.61,
      "gananciaDinero": 35882.0,
      "valorizado": 53948.0,
      "titulo": {
        "simbolo": "C",
        "descripcion": "Citigroup",
        "pais": "argentina",
        "mercado": "bcba",
        "tipo": "CEDEARS",
        "plazo": "t1",
        "moneda": "peso_Argentino"
      },
      "parking": null
    },
    {
      "cantidad": 68.0,
      "comprometido": 0.0,
      "puntosVariacion": 0.0,
      "variacionDiaria": -1.13,
      "ultimoPrecio": 1168.0,
      "ppc": 495.89,
      "gananciaPorcentaje": 135.53,
      "gananciaDinero": 45703.5,
      "valorizado": 79424.0,
      "titulo": {
        "simbolo": "CEPU",
        "descripcion": "Central Puerto Sa",
        "pais": "argentina",
        "mercado": "bcba",
        "tipo": "ACCIONES",
        "plazo": "t1",
        "moneda": "peso_Argentino"
      },
      "parking": null
    },
    {
      "cantidad": 583.548,
      "comprometido": 0.0,
      "puntosVariacion": 94.29439,
      "variacionDiaria": -0.2,
      "ultimoPrecio": 94.29439,
      "ppc": 25.705,
      "gananciaPorcentaje": 266.83,
      "gananciaDinero": 40025.31,
      "valorizado": 55025.30269572,
      "titulo": {
        "simbolo": "CONIOLA",
        "descripcion": "Adcap Acciones",
        "pais": "argentina",
        "mercado": "bcba",
        "tipo": "FondoComundeInversion",
        "plazo": "t1",
        "moneda": "peso_Argentino"
      },
      "parking": null
    },
    {
      "cantidad": 255.766,
      "comprometido": 0.0,
      "puntosVariacion": 100.726238,
      "variacionDiaria": 0.12,
      "ultimoPrecio": 100.726238,
      "ppc": 39.098,
      "gananciaPorcentaje": 157.62,
      "gananciaDinero": 15762.35,
      "valorizado": 25762.346988308,
      "titulo": {
        "simbolo": "CRTAFAA",
        "descripcion": "Adcap Renta Fija",
        "pais": "argentina",
        "mercado": "bcba",
        "tipo": "FondoComundeInversion",
        "plazo": "t2",
        "moneda": "peso_Argentino"
      },
      "parking": null
    },
    {
      "cantidad": 108.0,
      "comprometido": 0.0,
      "puntosVariacion": 0.0,
      "variacionDiaria": -1.07,
      "ultimoPrecio": 55300.0,
      "ppc": 48282.778,
      "gananciaPorcentaje": 14.53,
      "gananciaDinero": 7578.6,
      "valorizado": 59724.0,
      "titulo": {
        "simbolo": "GD35",
        "descripcion": "Bonos Rep. Arg. U$S Step Up V.09/07/35",
        "pais": "argentina",
        "mercado": "bcba",
        "tipo": "TitulosPublicos",
        "plazo": "t1",
        "moneda": "peso_Argentino"
      },
      "parking": null
    },
    {
      "cantidad": 76.0,
      "comprometido": 0.0,
      "puntosVariacion": 0.0,
      "variacionDiaria": -0.9,
      "ultimoPrecio": 4269.0,
      "ppc": 1615.991,
      "gananciaPorcentaje": 164.17,
      "gananciaDinero": 201628.7,
      "valorizado": 324444.0,
      "titulo": {
        "simbolo": "GGAL",
        "descripcion": "Grupo Financiero Galicia S.A",
        "pais": "argentina",
        "mercado": "bcba",
        "tipo": "ACCIONES",
        "plazo": "t1",
        "moneda": "peso_Argentino"
      },
      "parking": null
    },
    {
      "cantidad": 11.0,
      "comprometido": 0.0,
      "puntosVariacion": 0.0,
      "variacionDiaria": 1.03,
      "ultimoPrecio": 3970.0,
      "ppc": 1543.318,
      "gananciaPorcentaje": 157.23,
      "gananciaDinero": 26693.5,
      "valorizado": 43670.0,
      "titulo": {
        "simbolo": "GOOGL",
        "descripcion": "Google",
        "pais": "argentina",
        "mercado": "bcba",
        "tipo": "CEDEARS",
        "plazo": "t1",
        "moneda": "peso_Argentino"
      },
      "parking": null
    },
    {
      "cantidad": 3.0,
      "comprometido": 0.0,
      "puntosVariacion": 0.0,
      "variacionDiaria": -1.31,
      "ultimoPrecio": 17236.0,
      "ppc": 6122.333,
      "gananciaPorcentaje": 181.52,
      "gananciaDinero": 33341.0,
      "valorizado": 51708.0,
      "titulo": {
        "simbolo": "JPM",
        "descripcion": "Jpmorgan Chase & Co.",
        "pais": "argentina",
        "mercado": "bcba",
        "tipo": "CEDEARS",
        "plazo": "t1",
        "moneda": "peso_Argentino"
      },
      "parking": null
    },
    {
      "cantidad": 4.0,
      "comprometido": 0.0,
      "puntosVariacion": 0.0,
      "variacionDiaria": -2.01,
      "ultimoPrecio": 17506.0,
      "ppc": 6350.0,
      "gananciaPorcentaje": 175.68,
      "gananciaDinero": 44624.0,
      "valorizado": 70024.0,
      "titulo": {
        "simbolo": "MELI",
        "descripcion": "Mercadolibre",
        "pais": "argentina",
        "mercado": "bcba",
        "tipo": "CEDEARS",
        "plazo": "t1",
        "moneda": "peso_Argentino"
      },
      "parking": null
    },
    {
      "cantidad": 2.0,
      "comprometido": 0.0,
      "puntosVariacion": 0.0,
      "variacionDiaria": 1.52,
      "ultimoPrecio": 18470.0,
      "ppc": 8892.0,
      "gananciaPorcentaje": 107.71,
      "gananciaDinero": 19156.0,
      "valorizado": 36940.0,
      "titulo": {
        "simbolo": "MSFT",
        "descripcion": "Microsoft",
        "pais": "argentina",
        "mercado": "bcba",
        "tipo": "CEDEARS",
        "plazo": "t1",
        "moneda": "peso_Argentino"
      },
      "parking": null
    },
    {
      "cantidad": 42.0,
      "comprometido": 0.0,
      "puntosVariacion": 0.0,
      "variacionDiaria": -0.22,
      "ultimoPrecio": 2327.0,
      "ppc": 1059.524,
      "gananciaPorcentaje": 119.62,
      "gananciaDinero": 53234.0,
      "valorizado": 97734.0,
      "titulo": {
        "simbolo": "PAMP",
        "descripcion": "Pampa Energ\u00eda",
        "pais": "argentina",
        "mercado": "bcba",
        "tipo": "ACCIONES",
        "plazo": "t1",
        "moneda": "peso_Argentino"
      },
      "parking": null
    },
    {
      "cantidad": 3.0,
      "comprometido": 0.0,
      "puntosVariacion": 0.0,
      "variacionDiaria": 1.81,
      "ultimoPrecio": 30384.5,
      "ppc": 8784.5,
      "gananciaPorcentaje": 245.88,
      "gananciaDinero": 64800.0,
      "valorizado": 91153.5,
      "titulo": {
        "simbolo": "QQQ",
        "descripcion": "Etf Invesco Qqq Trust",
        "pais": "argentina",
        "mercado": "bcba",
        "tipo": "CEDEARS",
        "plazo": "t1",
        "moneda": "peso_Argentino"
      },
      "parking": null
    },
    {
      "cantidad": 7.0,
      "comprometido": 0.0,
      "puntosVariacion": 0.0,
      "variacionDiaria": 0.98,
      "ultimoPrecio": 34999.5,
      "ppc": 19946.571,
      "gananciaPorcentaje": 75.46,
      "gananciaDinero": 105370.5,
      "valorizado": 244996.5,
      "titulo": {
        "simbolo": "SPY",
        "descripcion": "Etf Spdr S&P 500",
        "pais": "argentina",
        "mercado": "bcba",
        "tipo": "CEDEARS",
        "plazo": "t1",
        "moneda": "peso_Argentino"
      },
      "parking": null
    },
    {
      "cantidad": 7.0,
      "comprometido": 0.0,
      "puntosVariacion": 0.0,
      "variacionDiaria": -0.07,
      "ultimoPrecio": 4665.0,
      "ppc": 1267.814,
      "gananciaPorcentaje": 267.95,
      "gananciaDinero": 23780.3,
      "valorizado": 32655.0,
      "titulo": {
        "simbolo": "TGSU2",
        "descripcion": "Transportadora Gas Del Sur",
        "pais": "argentina",
        "mercado": "bcba",
        "tipo": "ACCIONES",
        "plazo": "t1",
        "moneda": "peso_Argentino"
      },
      "parking": null
    },
    {
      "cantidad": 5613.0,
      "comprometido": 0.0,
      "puntosVariacion": 0.0,
      "variacionDiaria": 0.34,
      "ultimoPrecio": 1756.0,
      "ppc": 1750.0,
      "gananciaPorcentaje": 0.34,
      "gananciaDinero": 336.78,
      "valorizado": 98564.28,
      "titulo": {
        "simbolo": "TX26",
        "descripcion": "Bono Del Tesoro Boncer 2% $ 2026",
        "pais": "argentina",
        "mercado": "bcba",
        "tipo": "TitulosPublicos",
        "plazo": "t1",
        "moneda": "peso_Argentino"
      },
      "parking": null
    },
    {
      "cantidad": 48.0,
      "comprometido": 0.0,
      "puntosVariacion": 0.0,
      "variacionDiaria": -1.06,
      "ultimoPrecio": 973.0,
      "ppc": 813.0,
      "gananciaPorcentaje": 19.68,
      "gananciaDinero": 7680.0,
      "valorizado": 46704.0,
      "titulo": {
        "simbolo": "TXAR",
        "descripcion": "Ternium Argentina Sa",
        "pais": "argentina",
        "mercado": "bcba",
        "tipo": "ACCIONES",
        "plazo": "t1",
        "moneda": "peso_Argentino"
      },
      "parking": null
    },
    {
      "cantidad": 15.0,
      "comprometido": 0.0,
      "puntosVariacion": 0.0,
      "variacionDiaria": -0.73,
      "ultimoPrecio": 18617.0,
      "ppc": 3909.167,
      "gananciaPorcentaje": 376.23,
      "gananciaDinero": 220617.5,
      "valorizado": 279255.0,
      "titulo": {
        "simbolo": "VIST",
        "descripcion": "Vista Energy S.A.B. De C.V.",
        "pais": "argentina",
        "mercado": "bcba",
        "tipo": "CEDEARS",
        "plazo": "t1",
        "moneda": "peso_Argentino"
      },
      "parking": null
    },
    {
      "cantidad": 15.0,
      "comprometido": 0.0,
      "puntosVariacion": 0.0,
      "variacionDiaria": 1.55,
      "ultimoPrecio": 27156.0,
      "ppc": 12303.427,
      "gananciaPorcentaje": 120.71,
      "gananciaDinero": 222788.6,
      "valorizado": 407340.0,
      "titulo": {
        "simbolo": "YPFD",
        "descripcion": "Ypf",
        "pais": "argentina",
        "mercado": "bcba",
        "tipo": "ACCIONES",
        "plazo": "t1",
        "moneda": "peso_Argentino"
      },
      "parking": null
    }
  ]
}

In [43]:
data={
        "username": "Fedebohl",
        "password": "Fedecapo_01"
    }
data['username']

'Fedebohl'

In [59]:
import requests
from datetime import datetime, timedelta
import pandas as pd

class TokenManager:
    def __init__(self, username,password):
        self.token_info = None
        self.user_data={
                        'username':username,
                        'password':password
                        }
        self.load_user_data()
        self.token_url = 'https://api.invertironline.com/token'
        self.base_url = 'https://api.invertironline.com/api/v2'
        self.portfolio_url = f'{self.base_url}/portafolio'
        self.quotes_url = f'{self.base_url}/Cotizaciones/{{instrument}}/{{country}}/Todos'

    def load_user_data(self):
        self.username = self.user_data['username']
        self.password = self.user_data['password']

    def get_new_token(self):
        data = {
            'grant_type': 'password',
            'username': self.username,
            'password': self.password
        }
        headers = {'Content-Type': 'application/x-www-form-urlencoded'}
        response = requests.post(self.token_url, data=data, headers=headers)
        self.token_info = response.json()
        if 'error' in self.token_info:
            raise Exception(f"Error obtaining token: {self.token_info['error']}")
        self.token_info['expires_at'] = datetime.now() + timedelta(seconds=self.token_info['expires_in'])
    
    def refresh_token(self):
        data = {
            'grant_type': 'refresh_token',
            'refresh_token': self.token_info['refresh_token']
        }
        headers = {'Content-Type': 'application/x-www-form-urlencoded'}
        response = requests.post(self.token_url, data=data, headers=headers)
        new_token_info = response.json()
        if 'error' in new_token_info:
            raise Exception(f"Error refreshing token: {new_token_info['error']}")
        self.token_info.update(new_token_info)
        self.token_info['expires_at'] = datetime.now() + timedelta(seconds=self.token_info['expires_in'])

    def ensure_token(self):
        if not self.token_info or datetime.now() >= self.token_info['expires_at']:
            self.refresh_token() if self.token_info else self.get_new_token()

    def get_portfolio(self):
        self.ensure_token()
        headers = {'Authorization': f"Bearer {self.token_info['access_token']}"}
        response = requests.get(self.portfolio_url, headers=headers)
        if response.status_code != 200:
            raise Exception(f"Error fetching portfolio: {response.text}")
        return response.json()

    def get_quotes(self, instrument, country):
        self.ensure_token()
        url = self.quotes_url.format(instrument=instrument, country=country)
        headers = {'Authorization': f"Bearer {self.token_info['access_token']}"}
        response = requests.get(url, headers=headers)
        if response.status_code != 200:
            raise Exception(f"Error fetching {instrument} quotes: {response.text}")
        df=pd.DataFrame(response.json()['titulos'])
        return df[['simbolo','ultimoPrecio']]

In [51]:
df=pd.read_excel('Operaciones.xlsx')
df=df.sort_values(by='Fecha Liquidación', ascending=True)
df

,Fecha Liquidación,Mercado,Tipo Transacción,Descripción,Especie,Simbolo,Cantidad,Moneda,Precio Ponderado,Monto,Comisión y Derecho de Mercado,Iva Impuesto,Total,Tipo de Acción
60,2023-05-05,BCBA,Compra,Central Puerto Sa,322,CEPU,30,AR$,262.5,7875.0,45.68,9.59,7930.27,Accion
59,2023-05-05,BCBA,Compra,YPF,710,YPFD,8,AR$,4900.0,39200.0,227.36,47.75,39475.11,Accion
57,2023-06-06,BCBA,Compra,Central Puerto Sa,322,CEPU,20,AR$,343.0,6860.0,39.79,8.35,6908.14,Accion
56,2023-06-06,BCBA,Compra,Vista Energy S.A.B. De C.V.,8527,VIST,1,AR$,10760.0,10760.0,62.41,13.11,10835.52,Cedear
55,2023-06-06,BCBA,Venta,YPF,710,YPFD,1,AR$,5739.0,5739.0,33.29,6.99,5698.72,Accion
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,2024-05-20,BCBA,Compra,Bono Del Tesoro Boncer 2% $ 2026,5925,TX26,5613,AR$,1750.0,98227.5,500.96,0.00,98728.46,Bono
3,2024-05-20,BCBA,Compra,Bonos Rep. Arg. U$S Step Up V.09/07/35,81088,GD35,76,AR$,53250.0,40470.0,206.40,0.00,40676.40,Bono
2,2024-05-20,BCBA,Compra,BOPREAL Serie 3 Vto 31/05/26,9247,BPY26,100,AR$,90000.0,90000.0,459.00,0.00,90459.00,Bono
1,2024-05-21,BCBA,Compra,Bono Rep. Argentina Usd Step Up 2030,5921,AL30,97,AR$,62750.0,60867.5,310.43,0.00,61177.93,Bono
0,2024-05-28,BCBA,Compra,Bono Rep. Argentina Usd Step Up 2030,5921,AL30,16,AR$,65650.0,10504.0,53.57,0.00,10557.57,Bono

In [55]:
for i in range(len(df.index)):
    print(df.iloc[i],'\n')

Fecha Liquidación                2023-05-05 00:00:00
Mercado                                         BCBA
Tipo Transacción                              Compra
Descripción                        Central Puerto Sa
Especie                                          322
Simbolo                                         CEPU
Cantidad                                          30
Moneda                                           AR$
Precio Ponderado                               262.5
Monto                                         7875.0
Comisión y Derecho de Mercado                  45.68
Iva Impuesto                                    9.59
Total                                        7930.27
Tipo de Acción                                Accion
Name: 60, dtype: object

Fecha Liquidación                2023-05-05 00:00:00
Mercado                                         BCBA
Tipo Transacción                              Compra
Descripción                                      YPF
Especie                                          710
Simbolo                                         YPFD
Cantidad                                           8
Moneda                                           AR$
Precio Ponderado                              4900.0
Monto                                        39200.0
Comisión y Derecho de Mercado                 227.36
Iva Impuesto                                   47.75
Total                                       39475.11
Tipo de Acción                                Accion
Name: 59, dtype: object

Fecha Liquidación                2023-06-06 00:00:00
Mercado                                         BCBA
Tipo Transacción                              Compra
Descripción                        Central Puerto Sa
Especie                                          322
Simbolo                                         CEPU
Cantidad                                          20
Moneda                                           AR$
Precio Ponderado                               343.0
Monto                                         6860.0
Comisión y Derecho de Mercado                  39.79
Iva Impuesto                                    8.35
Total                                        6908.14
Tipo de Acción                                Accion
Name: 57, dtype: object

Fecha Liquidación                        2023-06-06 00:00:00
Mercado                                                 BCBA
Tipo Transacción                                      Compra
Descripción                      Vista Energy S.A.B. De C.V.
Especie                                                 8527
Simbolo                                                 VIST
Cantidad                                                   1
Moneda                                                   AR$
Precio Ponderado                                     10760.0
Monto                                                10760.0
Comisión y Derecho de Mercado                          62.41
Iva Impuesto                                           13.11
Total                                               10835.52
Tipo de Acción                                        Cedear
Name: 56, dtype: object

Fecha Liquidación                2023-06-06 00:00:00
Mercado                                         BCBA
Tipo Transacción                               Venta
Descripción                                      YPF
Especie                                          710
Simbolo                                         YPFD
Cantidad                                           1
Moneda                                           AR$
Precio Ponderado                              5739.0
Monto                                         5739.0
Comisión y Derecho de Mercado                  33.29
Iva Impuesto                                    6.99
Total                                        5698.72
Tipo de Acción                                Accion
Name: 55, dtype: object

Fecha Liquidación                2023-06-06 00:00:00
Mercado                                         BCBA
Tipo Transacción                               Venta
Descripción                                      YPF
Especie                                          710
Simbolo                                         YPFD
Cantidad                                           1
Moneda                                           AR$
Precio Ponderado                              5714.0
Monto                                         5714.0
Comisión y Derecho de Mercado                  33.14
Iva Impuesto                                    6.96
Total                                         5673.9
Tipo de Acción                                Accion
Name: 54, dtype: object

Fecha Liquidación                        2023-06-06 00:00:00
Mercado                                                 BCBA
Tipo Transacción                                      Compra
Descripción                      Vista Energy S.A.B. De C.V.
Especie                                                 8527
Simbolo                                                 VIST
Cantidad                                                   2
Moneda                                                   AR$
Precio Ponderado                                     10760.0
Monto                                                21520.0
Comisión y Derecho de Mercado                         124.82
Iva Impuesto                                           26.22
Total                                               21671.04
Tipo de Acción                                        Cedear
Name: 53, dtype: object

Fecha Liquidación                2023-06-06 00:00:00
Mercado                                         BCBA
Tipo Transacción                              Compra
Descripción                       Meta Platforms Inc
Especie                                         8467
Simbolo                                         META
Cantidad                                           2
Moneda                                           AR$
Precio Ponderado                              5630.0
Monto                                        11260.0
Comisión y Derecho de Mercado                  65.31
Iva Impuesto                                   13.71
Total                                       11339.02
Tipo de Acción                                Cedear
Name: 58, dtype: object

Fecha Liquidación                2023-06-07 00:00:00
Mercado                                         BCBA
Tipo Transacción                              Compra
Descripción                         Etf Spdr S&P 500
Especie                                         8549
Simbolo                                          SPY
Cantidad                                           3
Moneda                                           AR$
Precio Ponderado                             10590.0
Monto                                        31770.0
Comisión y Derecho de Mercado                 184.27
Iva Impuesto                                    38.7
Total                                       31992.97
Tipo de Acción                                Cedear
Name: 52, dtype: object

Fecha Liquidación                         2023-06-08 00:00:00
Mercado                                                  BCBA
Tipo Transacción                                       Compra
Descripción                      Grupo Financiero Galicia S.A
Especie                                                   534
Simbolo                                                  GGAL
Cantidad                                                   27
Moneda                                                    AR$
Precio Ponderado                                        660.0
Monto                                                 17820.0
Comisión y Derecho de Mercado                          103.36
Iva Impuesto                                             21.7
Total                                                17945.06
Tipo de Acción                                         Accion
Name: 46, dtype: object

Fecha Liquidación                  2023-06-08 00:00:00
Mercado                                           BCBA
Tipo Transacción                                Compra
Descripción                      Etf Invesco Qqq Trust
Especie                                           8550
Simbolo                                            QQQ
Cantidad                                             4
Moneda                                             AR$
Precio Ponderado                                8784.5
Monto                                          35138.0
Comisión y Derecho de Mercado                    203.8
Iva Impuesto                                     42.79
Total                                         35384.59
Tipo de Acción                                  Cedear
Name: 47, dtype: object

Fecha Liquidación                2023-06-08 00:00:00
Mercado                                         BCBA
Tipo Transacción                              Compra
Descripción                                    Apple
Especie                                         8445
Simbolo                                         AAPL
Cantidad                                           1
Moneda                                           AR$
Precio Ponderado                              8885.0
Monto                                         8885.0
Comisión y Derecho de Mercado                  51.54
Iva Impuesto                                   10.82
Total                                        8947.36
Tipo de Acción                                Cedear
Name: 44, dtype: object

Fecha Liquidación                       2023-06-08 00:00:00
Mercado                                                BCBA
Tipo Transacción                                     Compra
Descripción                      Transportadora Gas del Sur
Especie                                                 617
Simbolo                                               TGSU2
Cantidad                                                  3
Moneda                                                  AR$
Precio Ponderado                                     1304.9
Monto                                                3914.7
Comisión y Derecho de Mercado                          22.7
Iva Impuesto                                           4.77
Total                                               3942.17
Tipo de Acción                                       Accion
Name: 49, dtype: object

Fecha Liquidación                         2023-06-08 00:00:00
Mercado                                                  BCBA
Tipo Transacción                                       Compra
Descripción                      Transportadora Gas del Norte
Especie                                                 30005
Simbolo                                                 TGNO4
Cantidad                                                    6
Moneda                                                    AR$
Precio Ponderado                                        738.0
Monto                                                  4428.0
Comisión y Derecho de Mercado                           25.68
Iva Impuesto                                             5.39
Total                                                 4459.07
Tipo de Acción                                         Accion
Name: 48, dtype: object

Fecha Liquidación                2023-06-08 00:00:00
Mercado                                         BCBA
Tipo Transacción                              Compra
Descripción                                   Google
Especie                                         8442
Simbolo                                        GOOGL
Cantidad                                           6
Moneda                                           AR$
Precio Ponderado                              1081.5
Monto                                         6489.0
Comisión y Derecho de Mercado                  37.64
Iva Impuesto                                     7.9
Total                                        6534.54
Tipo de Acción                                Cedear
Name: 51, dtype: object

Fecha Liquidación                2023-06-08 00:00:00
Mercado                                         BCBA
Tipo Transacción                              Compra
Descripción                            Pampa Energía
Especie                                          457
Simbolo                                         PAMP
Cantidad                                          32
Moneda                                           AR$
Precio Ponderado                               800.0
Monto                                        25600.0
Comisión y Derecho de Mercado                 148.48
Iva Impuesto                                   31.18
Total                                       25779.66
Tipo de Acción                                Accion
Name: 45, dtype: object

Fecha Liquidación                2023-06-08 00:00:00
Mercado                                         BCBA
Tipo Transacción                              Compra
Descripción                                    Aluar
Especie                                            7
Simbolo                                         ALUA
Cantidad                                           7
Moneda                                           AR$
Precio Ponderado                               373.0
Monto                                         2611.0
Comisión y Derecho de Mercado                  15.15
Iva Impuesto                                    3.18
Total                                        2629.33
Tipo de Acción                                Accion
Name: 50, dtype: object

Fecha Liquidación                2023-06-12 00:00:00
Mercado                                         BCBA
Tipo Transacción                              Compra
Descripción                              Banco Macro
Especie                                          111
Simbolo                                          BMA
Cantidad                                           9
Moneda                                           AR$
Precio Ponderado                              1109.0
Monto                                         9981.0
Comisión y Derecho de Mercado                  57.89
Iva Impuesto                                   12.16
Total                                       10051.05
Tipo de Acción                                Accion
Name: 43, dtype: object

Fecha Liquidación                2023-06-12 00:00:00
Mercado                                         BCBA
Tipo Transacción                               Venta
Descripción                       Meta Platforms Inc
Especie                                         8467
Simbolo                                         META
Cantidad                                           2
Moneda                                           AR$
Precio Ponderado                              5381.5
Monto                                        10763.0
Comisión y Derecho de Mercado                  62.43
Iva Impuesto                                   13.11
Total                                       10687.46
Tipo de Acción                                Cedear
Name: 42, dtype: object

Fecha Liquidación                         2023-06-15 00:00:00
Mercado                                                  BCBA
Tipo Transacción                                       Compra
Descripción                      Transportadora Gas del Norte
Especie                                                 30005
Simbolo                                                 TGNO4
Cantidad                                                    7
Moneda                                                    AR$
Precio Ponderado                                        684.0
Monto                                                  4788.0
Comisión y Derecho de Mercado                            7.25
Iva Impuesto                                             1.52
Total                                                 4796.77
Tipo de Acción                                         Accion
Name: 41, dtype: object

Fecha Liquidación                         2023-06-15 00:00:00
Mercado                                                  BCBA
Tipo Transacción                                        Venta
Descripción                      Transportadora Gas del Norte
Especie                                                 30005
Simbolo                                                 TGNO4
Cantidad                                                    6
Moneda                                                    AR$
Precio Ponderado                                       681.92
Monto                                                  4091.5
Comisión y Derecho de Mercado                           23.73
Iva Impuesto                                             4.99
Total                                                 4062.78
Tipo de Acción                                         Accion
Name: 40, dtype: object

Fecha Liquidación                         2023-06-16 00:00:00
Mercado                                                  BCBA
Tipo Transacción                                        Venta
Descripción                      Transportadora Gas del Norte
Especie                                                 30005
Simbolo                                                 TGNO4
Cantidad                                                    7
Moneda                                                    AR$
Precio Ponderado                                        669.0
Monto                                                  4683.0
Comisión y Derecho de Mercado                           27.17
Iva Impuesto                                             5.71
Total                                                 4650.12
Tipo de Acción                                         Accion
Name: 38, dtype: object

Fecha Liquidación                       2023-06-16 00:00:00
Mercado                                                BCBA
Tipo Transacción                                     Compra
Descripción                      Transportadora Gas del Sur
Especie                                                 617
Simbolo                                               TGSU2
Cantidad                                                  4
Moneda                                                  AR$
Precio Ponderado                                     1240.0
Monto                                                4960.0
Comisión y Derecho de Mercado                         28.77
Iva Impuesto                                           6.04
Total                                               4994.81
Tipo de Acción                                       Accion
Name: 39, dtype: object

Fecha Liquidación                2023-06-28 00:00:00
Mercado                                         BCBA
Tipo Transacción                              Compra
Descripción                                      YPF
Especie                                          710
Simbolo                                         YPFD
Cantidad                                           1
Moneda                                           AR$
Precio Ponderado                              7776.4
Monto                                         7776.4
Comisión y Derecho de Mercado                   45.1
Iva Impuesto                                    9.47
Total                                        7830.97
Tipo de Acción                                Accion
Name: 37, dtype: object

Fecha Liquidación                  2023-06-28 00:00:00
Mercado                                           BCBA
Tipo Transacción                                 Venta
Descripción                      Etf Invesco Qqq Trust
Especie                                           8550
Simbolo                                            QQQ
Cantidad                                             1
Moneda                                             AR$
Precio Ponderado                                9215.0

In [71]:
df.iloc[0]

Fecha Liquidación                2023-05-05 00:00:00
Mercado                                         BCBA
Tipo Transacción                              Compra
Descripción                        Central Puerto Sa
Especie                                          322
Simbolo                                         CEPU
Cantidad                                          30
Moneda                                           AR$
Precio Ponderado                               262.5
Monto                                         7875.0
Comisión y Derecho de Mercado                  45.68
Iva Impuesto                                    9.59
Total                                        7930.27
Tipo de Acción                                Accion
Name: 60, dtype: object

In [74]:
df.iloc[0]['Precio Ponderado']+5

267.5

In [84]:
a.at['CEPU', 'c1'] += 5

In [85]:
a

       c1  c2
CEPU    5   0
YPFD    0   0
VIST    0   0
META    0   0
SPY     0   0
GGAL    0   0
QQQ     0   0
AAPL    0   0
TGSU2   0   0
TGNO4   0   0
GOOGL   0   0
PAMP    0   0
ALUA    0   0
BMA     0   0
AL30    0   0
MELI    0   0
C       0   0
JPM     0   0
KO      0   0
AMZN    0   0
BRKB    0   0
MSFT    0   0
GD35    0   0
BPO27   0   0
TXAR    0   0
BPOC7   0   0
BPOD7   0   0
TX26    0   0
BPY26   0   0