In [ ]:
import json
import requests

class Token:

    def __init__(self, file_data):
        self.URL = 'https://api.invertironline.com/token'
        self.Host = 'api.invertironline.com'
        self.ContentType = 'application/x-www-form-urlencoded'
        self.granttype = 'password'
        self.file_data = file_data

        with open(self.file_data) as json_file:
            self.user_data = json.load(json_file)

        self.data = {
            'Host': self.Host,
            'username': self.user_data[0]['username'],
            'password': self.user_data[0]['password'],
            'grant_type': self.granttype
        }

        self.headers = {'Content-Type': self.ContentType}

    def get_token(self):
        r = requests.post(url=self.URL, data=self.data, headers=self.headers)
        data = r.json()

        if 'error' in data.keys():
            print('Error found: ' + data['error'])
        else:
            print('Access Token: ' + data['access_token'])
            print('Refresh Token: ' + data['refresh_token'])
            print('Expires: ' + data['.expires'])

# Uso de la clase Token
if __name__ == '__main__':
    token_obj = Token('user_data.json')
    token_obj.get_token()

In [ ]:
import json
import requests
from datetime import datetime, timedelta

class TokenManager:

    def __init__(self, file_data):
        self.file_data = file_data
        self.token_info = None
        self.load_user_data()
        self.token_url = 'https://api.invertironline.com/token'
        self.portfolio_url = 'https://api.invertironline.com/api/v2/portafolio'

    def load_user_data(self):
        with open(self.file_data) as json_file:
            self.user_data = json.load(json_file)
            self.username = self.user_data[0]['username']
            self.password = self.user_data[0]['password']

    def get_new_token(self):
        data = {
            'grant_type': 'password',
            'username': self.username,
            'password': self.password
        }
        headers = {'Content-Type': 'application/x-www-form-urlencoded'}
        response = requests.post(self.token_url, data=data, headers=headers)
        self.token_info = response.json()
        if 'error' in self.token_info:
            raise Exception(f"Error obtaining token: {self.token_info['error']}")
        self.token_info['expires_at'] = datetime.now() + timedelta(seconds=self.token_info['expires_in'])
    
    def refresh_token(self):
        data = {
            'grant_type': 'refresh_token',
            'refresh_token': self.token_info['refresh_token']
        }
        headers = {'Content-Type': 'application/x-www-form-urlencoded'}
        response = requests.post(self.token_url, data=data, headers=headers)
        new_token_info = response.json()
        if 'error' in new_token_info:
            raise Exception(f"Error refreshing token: {new_token_info['error']}")
        self.token_info.update(new_token_info)
        self.token_info['expires_at'] = datetime.now() + timedelta(seconds=self.token_info['expires_in'])

    def ensure_token(self):
        if not self.token_info or datetime.now() >= self.token_info['expires_at']:
            self.refresh_token() if self.token_info else self.get_new_token()

    def get_portfolio(self):
        self.ensure_token()
        headers = {'Authorization': f"Bearer {self.token_info['access_token']}"}
        response = requests.get(self.portfolio_url, headers=headers)
        if response.status_code != 200:
            raise Exception(f"Error fetching portfolio: {response.text}")
        return response.json()

if __name__ == '__main__':
    token_manager = TokenManager('user_data.json')
    portfolio = token_manager.get_portfolio()
    print(json.dumps(portfolio, indent=2))

In [ ]:
data={
        "username": "Fedebohl",
        "password": "Fedecapo_01"
    }
data['username']

In [ ]:
import requests
from datetime import datetime, timedelta
import pandas as pd

class TokenManager:
    def __init__(self, username,password):
        self.token_info = None
        self.user_data={
                        'username':username,
                        'password':password
                        }
        self.load_user_data()
        self.token_url = 'https://api.invertironline.com/token'
        self.base_url = 'https://api.invertironline.com/api/v2'
        self.portfolio_url = f'{self.base_url}/portafolio'
        self.quotes_url = f'{self.base_url}/Cotizaciones/{{instrument}}/{{country}}/Todos'

    def load_user_data(self):
        self.username = self.user_data['username']
        self.password = self.user_data['password']

    def get_new_token(self):
        data = {
            'grant_type': 'password',
            'username': self.username,
            'password': self.password
        }
        headers = {'Content-Type': 'application/x-www-form-urlencoded'}
        response = requests.post(self.token_url, data=data, headers=headers)
        self.token_info = response.json()
        if 'error' in self.token_info:
            raise Exception(f"Error obtaining token: {self.token_info['error']}")
        self.token_info['expires_at'] = datetime.now() + timedelta(seconds=self.token_info['expires_in'])
    
    def refresh_token(self):
        data = {
            'grant_type': 'refresh_token',
            'refresh_token': self.token_info['refresh_token']
        }
        headers = {'Content-Type': 'application/x-www-form-urlencoded'}
        response = requests.post(self.token_url, data=data, headers=headers)
        new_token_info = response.json()
        if 'error' in new_token_info:
            raise Exception(f"Error refreshing token: {new_token_info['error']}")
        self.token_info.update(new_token_info)
        self.token_info['expires_at'] = datetime.now() + timedelta(seconds=self.token_info['expires_in'])

    def ensure_token(self):
        if not self.token_info or datetime.now() >= self.token_info['expires_at']:
            self.refresh_token() if self.token_info else self.get_new_token()

    def get_portfolio(self):
        self.ensure_token()
        headers = {'Authorization': f"Bearer {self.token_info['access_token']}"}
        response = requests.get(self.portfolio_url, headers=headers)
        if response.status_code != 200:
            raise Exception(f"Error fetching portfolio: {response.text}")
        return response.json()

    def get_quotes(self, instrument, country):
        self.ensure_token()
        url = self.quotes_url.format(instrument=instrument, country=country)
        headers = {'Authorization': f"Bearer {self.token_info['access_token']}"}
        response = requests.get(url, headers=headers)
        if response.status_code != 200:
            raise Exception(f"Error fetching {instrument} quotes: {response.text}")
        df=pd.DataFrame(response.json()['titulos'])
        return df[['simbolo','ultimoPrecio']]

In [ ]:
df=pd.read_excel('Operaciones.xlsx')
df=df.sort_values(by='Fecha Liquidación', ascending=True)
df

In [ ]:
for i in range(len(df.index)):
    print(df.iloc[i],'\n')

In [ ]:
df.iloc[0]

In [1]:
from IOL import TokenManager as tm
token=tm('Fedebohl','Fedecapo_01')

In [2]:
token.get_new_token()

In [3]:
token.token_info

{'access_token': 'eyJhbGciOiJSUzI1NiIsInR5cCI6ImF0K2p3dCJ9.eyJzdWIiOiI2NDk1MjgiLCJJRCI6IjY0OTUyOCIsImp0aSI6IjZlMDcxNjkyLTdmZDMtNDMyZC1hYzg1LWIwZWI1YjZkMjRkNyIsImNvbnN1bWVyX3R5cGUiOiIxIiwidGllbmVfY3VlbnRhIjoiVHJ1ZSIsInRpZW5lX3Byb2R1Y3RvX2J1cnNhdGlsIjoiVHJ1ZSIsInRpZW5lX3Byb2R1Y3RvX2FwaSI6IlRydWUiLCJ0aWVuZV9UeUMiOiJUcnVlIiwibmJmIjoxNzE3Njc4NDE5LCJleHAiOjE3MTc2NzkzMTksImlhdCI6MTcxNzY3ODQxOSwiaXNzIjoiSU9MT2F1dGhTZXJ2ZXIiLCJhdWQiOiJJT0xPYXV0aFNlcnZlciJ9.dV25LeAbQ-3sb2OUnyQgb-1wsFkURaYXBqMRbTpOoy7CwBIRvwEXoRSPAebc0OdhlS6SufF53-6dVlyEz0eqsMtIGvGpvmUQ5BEVRPW67cdyXCyMtZs4PiejaelX81s4NVYgkJv5mfo0WRf1KKsbZNtygJA2yiQ2OpTfO5XrYqnC2PInClWqWz4hHWKSyf5rmFeHuPmtjODk-1rh_WEOafY8mmqIJgLdL_JzPKE9VftpyNM30uVCtuxv4sGEJ0pdnznIXEjevBtW97zAiN7hBOpkFUlviSa2E-UR11j3qMXCzNz4YXbsYoORyWLSPj3U-ctvCF_zbwLDiuPiuhsaWw',
 'token_type': 'bearer',
 'expires_in': 1200,
 'refresh_token': 'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDk1MjgiLCJqdGkiOiJjOGI4MzgyYi05ZmI2LTQ0YzQtOGE5Ny0yZDFmMDRiMDkzYjMiLCJydF9mYW1pbHkiOiI2N2Y0NGJkMy0wYjljLTQyZWEtYTk3Ni1hMDkxNmUzNmUwMzQiLCJuYmYiOjE3MTc2Nzg0MTksImV4cCI6MTcxNzY3OTYxOSwiaWF0IjoxNzE3Njc4NDE5LCJpc3MiOiJJT0xPYXV0aFNlcnZlciIsImF1ZCI6IklPTE9hdXRoU2VydmVyIn0.mwlanQgQ0cwOGogr4ew5b3HnCoLU7C_G0rrsDmXYUFmLPJ8PjZFjeP3EIstMfKWqJceFD7RX8fF9o8bhwNQA-Kc8i4svMrBk1-06fKYIySDjYHEPT3R0yH1hwFxQrj_QM3p88IMf9gWDhmIZO7uaXuRCy3vjvgtN63O0sWaC0Kc2tGO7N4mM8WoMsLyClhYQ-gtiFAsJMmkCdDirw25pfaZQdGmzAnOPrJf8Cbmiwii5tTzmdKpRLF9M1s3NVjFpExKpiJqc6oEEdR7sZGtQxzR53LeCTgolITTpX25q58jMcttIVqtEgsh0jjNYxufHDEDYf5ijtZFB0oAg8QGEGQ',
 '.issued': 'Thu, 06 Jun 2024 12:53:39 GMT',
 '.expires': 'Thu, 06 Jun 2024 13:08:39 GMT',
 '.refreshexpires': 'Thu, 06 Jun 2024 13:13:39 GMT',
 'expires_at': datetime.datetime(2024, 6, 6, 10, 13, 39, 141480)}

In [7]:
token.token_info

{'access_token': 'eyJhbGciOiJSUzI1NiIsInR5cCI6ImF0K2p3dCJ9.eyJzdWIiOiI2NDk1MjgiLCJJRCI6IjY0OTUyOCIsImp0aSI6IjZlMDcxNjkyLTdmZDMtNDMyZC1hYzg1LWIwZWI1YjZkMjRkNyIsImNvbnN1bWVyX3R5cGUiOiIxIiwidGllbmVfY3VlbnRhIjoiVHJ1ZSIsInRpZW5lX3Byb2R1Y3RvX2J1cnNhdGlsIjoiVHJ1ZSIsInRpZW5lX3Byb2R1Y3RvX2FwaSI6IlRydWUiLCJ0aWVuZV9UeUMiOiJUcnVlIiwibmJmIjoxNzE3Njc4NDE5LCJleHAiOjE3MTc2NzkzMTksImlhdCI6MTcxNzY3ODQxOSwiaXNzIjoiSU9MT2F1dGhTZXJ2ZXIiLCJhdWQiOiJJT0xPYXV0aFNlcnZlciJ9.dV25LeAbQ-3sb2OUnyQgb-1wsFkURaYXBqMRbTpOoy7CwBIRvwEXoRSPAebc0OdhlS6SufF53-6dVlyEz0eqsMtIGvGpvmUQ5BEVRPW67cdyXCyMtZs4PiejaelX81s4NVYgkJv5mfo0WRf1KKsbZNtygJA2yiQ2OpTfO5XrYqnC2PInClWqWz4hHWKSyf5rmFeHuPmtjODk-1rh_WEOafY8mmqIJgLdL_JzPKE9VftpyNM30uVCtuxv4sGEJ0pdnznIXEjevBtW97zAiN7hBOpkFUlviSa2E-UR11j3qMXCzNz4YXbsYoORyWLSPj3U-ctvCF_zbwLDiuPiuhsaWw',
 'token_type': 'bearer',
 'expires_in': 1200,
 'refresh_token': 'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDk1MjgiLCJqdGkiOiJjOGI4MzgyYi05ZmI2LTQ0YzQtOGE5Ny0yZDFmMDRiMDkzYjMiLCJydF9mYW1pbHkiOiI2N2Y0NGJkMy0wYjljLTQyZWEtYTk3Ni1hMDkxNmUzNmUwMzQiLCJuYmYiOjE3MTc2Nzg0MTksImV4cCI6MTcxNzY3OTYxOSwiaWF0IjoxNzE3Njc4NDE5LCJpc3MiOiJJT0xPYXV0aFNlcnZlciIsImF1ZCI6IklPTE9hdXRoU2VydmVyIn0.mwlanQgQ0cwOGogr4ew5b3HnCoLU7C_G0rrsDmXYUFmLPJ8PjZFjeP3EIstMfKWqJceFD7RX8fF9o8bhwNQA-Kc8i4svMrBk1-06fKYIySDjYHEPT3R0yH1hwFxQrj_QM3p88IMf9gWDhmIZO7uaXuRCy3vjvgtN63O0sWaC0Kc2tGO7N4mM8WoMsLyClhYQ-gtiFAsJMmkCdDirw25pfaZQdGmzAnOPrJf8Cbmiwii5tTzmdKpRLF9M1s3NVjFpExKpiJqc6oEEdR7sZGtQxzR53LeCTgolITTpX25q58jMcttIVqtEgsh0jjNYxufHDEDYf5ijtZFB0oAg8QGEGQ',
 '.issued': 'Thu, 06 Jun 2024 12:53:39 GMT',
 '.expires': 'Thu, 06 Jun 2024 13:08:39 GMT',
 '.refreshexpires': 'Thu, 06 Jun 2024 13:13:39 GMT',
 'expires_at': datetime.datetime(2024, 6, 6, 10, 13, 39, 141480)}

In [4]:
df=token.get_portfolio()

In [5]:
df

{'pais': 'argentina',
 'activos': [{'cantidad': 4.0,
   'comprometido': 0.0,
   'puntosVariacion': 0.0,
   'variacionDiaria': 0.0,
   'ultimoPrecio': 12832.0,
   'ppc': 5832.5,
   'gananciaPorcentaje': 120.0,
   'gananciaDinero': 27998.0,
   'valorizado': 51328.0,
   'titulo': {'simbolo': 'AAPL',
    'descripcion': 'Apple',
    'pais': 'argentina',
    'mercado': 'bcba',
    'tipo': 'CEDEARS',
    'plazo': 't1',
    'moneda': 'peso_Argentino'},
   'parking': None},
  {'cantidad': 555.0,
   'comprometido': 0.0,
   'puntosVariacion': 0.0,
   'variacionDiaria': 0.0,
   'ultimoPrecio': 67170.0,
   'ppc': 40964.09,
   'gananciaPorcentaje': 63.97,
   'gananciaDinero': 145442.8,
   'valorizado': 372793.5,
   'titulo': {'simbolo': 'AL30',
    'descripcion': 'Bono Rep. Argentina Usd Step Up 2030',
    'pais': 'argentina',
    'mercado': 'bcba',
    'tipo': 'TitulosPublicos',
    'plazo': 't1',
    'moneda': 'peso_Argentino'},
   'parking': None},
  {'cantidad': 30.0,
   'comprometido': 0.0,
   'puntosVariacion': 0.0,
   'variacionDiaria': 0.0,
   'ultimoPrecio': 965.5,
   'ppc': 597.717,
   'gananciaPorcentaje': 61.53,
   'gananciaDinero': 11033.5,
   'valorizado': 28965.0,
   'titulo': {'simbolo': 'ALUA',
    'descripcion': 'Aluar',
    'pais': 'argentina',
    'mercado': 'bcba',
    'tipo': 'ACCIONES',
    'plazo': 't1',
    'moneda': 'peso_Argentino'},
   'parking': None},
  {'cantidad': 14.0,
   'comprometido': 0.0,
   'puntosVariacion': 0.0,
   'variacionDiaria': 0.0,
   'ultimoPrecio': 1657.0,
   'ppc': 699.0,
   'gananciaPorcentaje': 137.05,
   'gananciaDinero': 13412.0,
   'valorizado': 23198.0,
   'titulo': {'simbolo': 'AMZN',
    'descripcion': 'Amazon',
    'pais': 'argentina',
    'mercado': 'bcba',
    'tipo': 'CEDEARS',
    'plazo': 't1',
    'moneda': 'peso_Argentino'},
   'parking': None},
  {'cantidad': 10.0,
   'comprometido': 0.0,
   'puntosVariacion': 0.0,
   'variacionDiaria': 0.0,
   'ultimoPrecio': 7877.15,
   'ppc': 1534.1,
   'gananciaPorcentaje': 413.47,
   'gananciaDinero': 63430.5,
   'valorizado': 78771.5,
   'titulo': {'simbolo': 'BMA',
    'descripcion': 'Banco Macro',
    'pais': 'argentina',
    'mercado': 'bcba',
    'tipo': 'ACCIONES',
    'plazo': 't1',
    'moneda': 'peso_Argentino'},
   'parking': None},
  {'cantidad': 38.0,
   'comprometido': 0.0,
   'puntosVariacion': 0.0,
   'variacionDiaria': 0.0,
   'ultimoPrecio': 115500.0,
   'ppc': 0.0,
   'gananciaPorcentaje': 0.0,
   'gananciaDinero': 0.0,
   'valorizado': 43890.0,
   'titulo': {'simbolo': 'BPOA7',
    'descripcion': 'Bopreal Serie 1A Vto. 31/10/27',
    'pais': 'argentina',
    'mercado': 'bcba',
    'tipo': 'TitulosPublicos',
    'plazo': 't1',
    'moneda': 'peso_Argentino'},
   'parking': None},
  {'cantidad': 38.0,
   'comprometido': 0.0,
   'puntosVariacion': 0.0,
   'variacionDiaria': 0.0,
   'ultimoPrecio': 103000.0,
   'ppc': 0.0,
   'gananciaPorcentaje': 0.0,
   'gananciaDinero': 0.0,
   'valorizado': 39140.0,
   'titulo': {'simbolo': 'BPOB7',
    'descripcion': 'Bopreal Serie 1B Vto. 31/10/27',
    'pais': 'argentina',
    'mercado': 'bcba',
    'tipo': 'TitulosPublicos',
    'plazo': 't1',
    'moneda': 'peso_Argentino'},
   'parking': None},
  {'cantidad': 176.0,
   'comprometido': 0.0,
   'puntosVariacion': 0.0,
   'variacionDiaria': 0.0,
   'ultimoPrecio': 91000.0,
   'ppc': 92857.159,
   'gananciaPorcentaje': -2.0,
   'gananciaDinero': -3268.6,
   'valorizado': 160160.0,
   'titulo': {'simbolo': 'BPOD7',
    'descripcion': 'Bopreal Serie 1D Vto. 31/10/27',
    'pais': 'argentina',
    'mercado': 'bcba',
    'tipo': 'TitulosPublicos',
    'plazo': 't1',
    'moneda': 'peso_Argentino'},
   'parking': None},
  {'cantidad': 100.0,
   'comprometido': 0.0,
   'puntosVariacion': 0.0,
   'variacionDiaria': 0.0,
   'ultimoPrecio': 99200.0,
   'ppc': 90000.0,
   'gananciaPorcentaje': 10.22,
   'gananciaDinero': 9200.0,
   'valorizado': 99200.0,
   'titulo': {'simbolo': 'BPY26',
    'descripcion': 'Bopreal Serie 3 Vto 31/05/26',
    'pais': 'argentina',
    'mercado': 'bcba',
    'tipo': 'TitulosPublicos',
    'plazo': 't1',
    'moneda': 'peso_Argentino'},
   'parking': None},
  {'cantidad': 1.0,
   'comprometido': 0.0,
   'puntosVariacion': 0.0,
   'variacionDiaria': 0.0,
   'ultimoPrecio': 24427.0,
   'ppc': 13158.0,
   'gananciaPorcentaje': 85.64,
   'gananciaDinero': 11269.0,
   'valorizado': 24427.0,
   'titulo': {'simbolo': 'BRKB',
    'descripcion': 'Berkshire Hathaway',
    'pais': 'argentina',
    'mercado': 'bcba',
    'tipo': 'CEDEARS',
    'plazo': 't1',
    'moneda': 'peso_Argentino'},
   'parking': None},
  {'cantidad': 2.0,
   'comprometido': 0.0,
   'puntosVariacion': 0.0,
   'variacionDiaria': 0.0,
   'ultimoPrecio': 26974.0,
   'ppc': 9033.0,
   'gananciaPorcentaje': 198.61,
   'gananciaDinero': 35882.0,
   'valorizado': 53948.0,
   'titulo': {'simbolo': 'C',
    'descripcion': 'Citigroup',
    'pais': 'argentina',
    'mercado': 'bcba',
    'tipo': 'CEDEARS',
    'plazo': 't1',
    'moneda': 'peso_Argentino'},
   'parking': None},
  {'cantidad': 68.0,
   'comprometido': 0.0,
   'puntosVariacion': 0.0,
   'variacionDiaria': 0.0,
   'ultimoPrecio': 1168.0,
   'ppc': 495.89,
   'gananciaPorcentaje': 135.53,
   'gananciaDinero': 45703.5,
   'valorizado': 79424.0,
   'titulo': {'simbolo': 'CEPU',
    'descripcion': 'Central Puerto Sa',
    'pais': 'argentina',
    'mercado': 'bcba',
    'tipo': 'ACCIONES',
    'plazo': 't1',
    'moneda': 'peso_Argentino'},
   'parking': None},
  {'cantidad': 583.548,
   'comprometido': 0.0,
   'puntosVariacion': 0.00039,
   'variacionDiaria': 0.0,
   'ultimoPrecio': 94.29439,
   'ppc': 25.705,
   'gananciaPorcentaje': 266.83,
   'gananciaDinero': 40025.31,
   'valorizado': 55025.30269572,
   'titulo': {'simbolo': 'CONIOLA',
    'descripcion': 'Adcap Acciones',
    'pais': 'argentina',
    'mercado': 'bcba',
    'tipo': 'FondoComundeInversion',
    'plazo': 't1',
    'moneda': 'peso_Argentino'},
   'parking': None},
  {'cantidad': 255.766,
   'comprometido': 0.0,
   'puntosVariacion': 0.000238,
   'variacionDiaria': 0.0,
   'ultimoPrecio': 100.726238,
   'ppc': 39.098,
   'gananciaPorcentaje': 157.62,
   'gananciaDinero': 15762.35,
   'valorizado': 25762.346988308,
   'titulo': {'simbolo': 'CRTAFAA',
    'descripcion': 'Adcap Renta Fija',
    'pais': 'argentina',
    'mercado': 'bcba',
    'tipo': 'FondoComundeInversion',
    'plazo': 't2',
    'moneda': 'peso_Argentino'},
   'parking': None},
  {'cantidad': 108.0,
   'comprometido': 0.0,
   'puntosVariacion': 0.0,
   'variacionDiaria': 0.0,
   'ultimoPrecio': 55300.0,
   'ppc': 48282.778,
   'gananciaPorcentaje': 14.53,
   'gananciaDinero': 7578.6,
   'valorizado': 59724.0,
   'titulo': {'simbolo': 'GD35',
    'descripcion': 'Bonos Rep. Arg. U$S Step Up V.09/07/35',
    'pais': 'argentina',
    'mercado': 'bcba',
    'tipo': 'TitulosPublicos',
    'plazo': 't1',
    'moneda': 'peso_Argentino'},
   'parking': None},
  {'cantidad': 76.0,
   'comprometido': 0.0,
   'puntosVariacion': 0.0,
   'variacionDiaria': 0.0,
   'ultimoPrecio': 4269.0,
   'ppc': 1615.991,
   'gananciaPorcentaje': 164.17,
   'gananciaDinero': 201628.7,
   'valorizado': 324444.0,
   'titulo': {'simbolo': 'GGAL',
    'descripcion': 'Grupo Financiero Galicia S.A',
    'pais': 'argentina',
    'mercado': 'bcba',
    'tipo': 'ACCIONES',
    'plazo': 't1',
    'moneda': 'peso_Argentino'},
   'parking': None},
  {'cantidad': 11.0,
   'comprometido': 0.0,
   'puntosVariacion': 0.0,
   'variacionDiaria': 0.0,
   'ultimoPrecio': 3970.0,
   'ppc': 1543.318,
   'gananciaPorcentaje': 157.23,
   'gananciaDinero': 26693.5,
   'valorizado': 43670.0,
   'titulo': {'simbolo': 'GOOGL',
    'descripcion': 'Google',
    'pais': 'argentina',
    'mercado': 'bcba',
    'tipo': 'CEDEARS',
    'plazo': 't1',
    'moneda': 'peso_Argentino'},
   'parking': None},
  {'cantidad': 3.0,
   'comprometido': 0.0,
   'puntosVariacion': 0.0,
   'variacionDiaria': 0.0,
   'ultimoPrecio': 17236.0,
   'ppc': 6122.333,
   'gananciaPorcentaje': 181.52,
   'gananciaDinero': 33341.0,
   'valorizado': 51708.0,
   'titulo': {'simbolo': 'JPM',
    'descripcion': 'Jpmorgan Chase & Co.',
    'pais': 'argentina',
    'mercado': 'bcba',
    'tipo': 'CEDEARS',
    'plazo': 't1',
    'moneda': 'peso_Argentino'},
   'parking': None},
  {'cantidad': 4.0,
   'comprometido': 0.0,
   'puntosVariacion': 0.0,
   'variacionDiaria': 0.0,
   'ultimoPrecio': 17506.0,
   'ppc': 6350.0,
   'gananciaPorcentaje': 175.68,
   'gananciaDinero': 44624.0,
   'valorizado': 70024.0,
   'titulo': {'simbolo': 'MELI',
    'descripcion': 'Mercadolibre',
    'pais': 'argentina',
    'mercado': 'bcba',
    'tipo': 'CEDEARS',
    'plazo': 't1',
    'moneda': 'peso_Argentino'},
   'parking': None},
  {'cantidad': 2.0,
   'comprometido': 0.0,
   'puntosVariacion': 0.0,
   'variacionDiaria': 0.0,
   'ultimoPrecio': 18470.0,
   'ppc': 8892.0,
   'gananciaPorcentaje': 107.71,
   'gananciaDinero': 19156.0,
   'valorizado': 36940.0,
   'titulo': {'simbolo': 'MSFT',
    'descripcion': 'Microsoft',
    'pais': 'argentina',
    'mercado': 'bcba',
    'tipo': 'CEDEARS',
    'plazo': 't1',
    'moneda': 'peso_Argentino'},
   'parking': None},
  {'cantidad': 42.0,
   'comprometido': 0.0,
   'puntosVariacion': 0.0,
   'variacionDiaria': 0.0,
   'ultimoPrecio': 2327.0,
   'ppc': 1059.524,
   'gananciaPorcentaje': 119.62,
   'gananciaDinero': 53234.0,
   'valorizado': 97734.0,
   'titulo': {'simbolo': 'PAMP',
    'descripcion': 'Pampa Energía',
    'pais': 'argentina',
    'mercado': 'bcba',
    'tipo': 'ACCIONES',
    'plazo': 't1',
    'moneda': 'peso_Argentino'},
   'parking': None},
  {'cantidad': 3.0,
   'comprometido': 0.0,
   'puntosVariacion': 0.0,
   'variacionDiaria': 0.0,
   'ultimoPrecio': 30384.5,
   'ppc': 8784.5,
   'gananciaPorcentaje': 245.88,
   'gananciaDinero': 64800.0,
   'valorizado': 91153.5,
   'titulo': {'simbolo': 'QQQ',
    'descripcion': 'Etf Invesco Qqq Trust',
    'pais': 'argentina',
    'mercado': 'bcba',
    'tipo': 'CEDEARS',
    'plazo': 't1',
    'moneda': 'peso_Argentino'},
   'parking': None},
  {'cantidad': 7.0,
   'comprometido': 0.0,
   'puntosVariacion': 0.0,
   'variacionDiaria': 0.0,
   'ultimoPrecio': 34999.5,
   'ppc': 19946.571,
   'gananciaPorcentaje': 75.46,
   'gananciaDinero': 105370.5,
   'valorizado': 244996.5,
   'titulo': {'simbolo': 'SPY',
    'descripcion': 'Etf Spdr S&P 500',
    'pais': 'argentina',
    'mercado': 'bcba',
    'tipo': 'CEDEARS',
    'plazo': 't1',
    'moneda': 'peso_Argentino'},
   'parking': None},
  {'cantidad': 7.0,
   'comprometido': 0.0,
   'puntosVariacion': 0.0,
   'variacionDiaria': 0.0,
   'ultimoPrecio': 4665.0,
   'ppc': 1267.814,
   'gananciaPorcentaje': 267.95,
   'gananciaDinero': 23780.3,
   'valorizado': 32655.0,
   'titulo': {'simbolo': 'TGSU2',
    'descripcion': 'Transportadora Gas Del Sur',
    'pais': 'argentina',
    'mercado': 'bcba',
    'tipo': 'ACCIONES',
    'plazo': 't1',
    'moneda': 'peso_Argentino'},
   'parking': None},
  {'cantidad': 5613.0,
   'comprometido': 0.0,
   'puntosVariacion': 0.0,
   'variacionDiaria': 0.0,
   'ultimoPrecio': 1756.0,
   'ppc': 1750.0,
   'gananciaPorcentaje': 0.34,
   'gananciaDinero': 336.78,
   'valorizado': 98564.28,
   'titulo': {'simbolo': 'TX26',
    'descripcion': 'Bono Del Tesoro Boncer 2% $ 2026',
    'pais': 'argentina',
    'mercado': 'bcba',
    'tipo': 'TitulosPublicos',
    'plazo': 't1',
    'moneda': 'peso_Argentino'},
   'parking': None},
  {'cantidad': 48.0,
   'comprometido': 0.0,
   'puntosVariacion': 0.0,
   'variacionDiaria': 0.0,
   'ultimoPrecio': 973.0,
   'ppc': 813.0,
   'gananciaPorcentaje': 19.68,
   'gananciaDinero': 7680.0,
   'valorizado': 46704.0,
   'titulo': {'simbolo': 'TXAR',
    'descripcion': 'Ternium Argentina Sa',
    'pais': 'argentina',
    'mercado': 'bcba',
    'tipo': 'ACCIONES',
    'plazo': 't1',
    'moneda': 'peso_Argentino'},
   'parking': None},
  {'cantidad': 15.0,
   'comprometido': 0.0,
   'puntosVariacion': 0.0,
   'variacionDiaria': 0.0,
   'ultimoPrecio': 18617.0,
   'ppc': 3909.167,
   'gananciaPorcentaje': 376.23,
   'gananciaDinero': 220617.5,
   'valorizado': 279255.0,
   'titulo': {'simbolo': 'VIST',
    'descripcion': 'Vista Energy S.A.B. De C.V.',
    'pais': 'argentina',
    'mercado': 'bcba',
    'tipo': 'CEDEARS',
    'plazo': 't1',
    'moneda': 'peso_Argentino'},
   'parking': None},
  {'cantidad': 15.0,
   'comprometido': 0.0,
   'puntosVariacion': 0.0,
   'variacionDiaria': 0.0,
   'ultimoPrecio': 27156.0,
   'ppc': 12303.427,
   'gananciaPorcentaje': 120.71,
   'gananciaDinero': 222788.6,
   'valorizado': 407340.0,
   'titulo': {'simbolo': 'YPFD',
    'descripcion': 'Ypf',
    'pais': 'argentina',
    'mercado': 'bcba',
    'tipo': 'ACCIONES',
    'plazo': 't1',
    'moneda': 'peso_Argentino'},
   'parking': None}]}

In [6]:
token.get_quotes('Bonos','argentina')

https://api.invertironline.com/api/v2/Cotizaciones/Bonos/argentina/Todos

KeyError: "None of [Index(['simbolo', 'ultimoPrecio'], dtype='object')] are in the [columns]"

In [34]:
token.refresh_token()
token.token_info

{'access_token': 'eyJhbGciOiJSUzI1NiIsInR5cCI6ImF0K2p3dCJ9.eyJzdWIiOiI2NDk1MjgiLCJJRCI6IjY0OTUyOCIsImp0aSI6Ijg0YzZmY2ZiLTg4ZDctNGM4My04ZDQzLTMwZjMwOTc5OTRmZSIsImNvbnN1bWVyX3R5cGUiOiIxIiwidGllbmVfY3VlbnRhIjoiVHJ1ZSIsInRpZW5lX3Byb2R1Y3RvX2J1cnNhdGlsIjoiVHJ1ZSIsInRpZW5lX3Byb2R1Y3RvX2FwaSI6IlRydWUiLCJ0aWVuZV9UeUMiOiJUcnVlIiwibmJmIjoxNzE3Njc5NTE2LCJleHAiOjE3MTc2ODA0MTYsImlhdCI6MTcxNzY3OTUxNiwiaXNzIjoiSU9MT2F1dGhTZXJ2ZXIiLCJhdWQiOiJJT0xPYXV0aFNlcnZlciJ9.TtcQC_tBSqSAOHFm6yGd4SWg1ZT9fBmOihmNh3_6rLooygPq2-gwIBz_Kdya154RUh-XMe56RfVJg3x3m1ra81KblwFC2wppRY_QDPdqk2S6D_miiMtUh3F-npsyX5p_XQ4vZF1AXmt04apWMjHFDJBcDa8HTLE5sge7hpFMHlQbax6asA_b1sd8UYAWG70mgBPTf2GRVtyfPt8-OFwFq-deUtsskUXXO4fI1FgHedIUuJ2YyxGsbWdUVqF1fU64ckaZ8iSNP3qQyfL8mn5Q1Qv9gLgg07dO8JEmnAerkY3Z1V0WwMGENRIlAnZMTfQsTadL8DzcszTi4qJyxeHr_A',
 'token_type': 'bearer',
 'expires_in': 1200,
 'refresh_token': 'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDk1MjgiLCJqdGkiOiIwYmI3YjQ0Yi0zYmIyLTRkZTktOTUxZi1mNzVmZjA4Mjk2OGYiLCJydF9mYW1pbHkiOiI2N2Y0NGJkMy0wYjljLTQyZWEtYTk3Ni1hMDkxNmUzNmUwMzQiLCJuYmYiOjE3MTc2Nzk1MTYsImV4cCI6MTcxNzY4MDcxNiwiaWF0IjoxNzE3Njc5NTE2LCJpc3MiOiJJT0xPYXV0aFNlcnZlciIsImF1ZCI6IklPTE9hdXRoU2VydmVyIn0.JL9PjoobsE9zi-kB_NQuusodzCJCiG3Pw_Y-TbUuaVnhuZjqkOKFqHjitgJwbzeCxLj-FDwCqKV3wTQlUiFMApQ1__mrvLMO_yXvdYJAtpQXUemDpgxDmYNfAk4y2zA9p47IsrrsdHRw6u5W0hoSno3b1KU8NBvAxrQ4oEtw-ltxMOko3AdsW5eC1ucDwvp-b67QL971CG2zdH9Mblqy-AtQECGn12GyFFRldcS88xUQHEjYjtgh0WZ8z9TxGzaodHsa0WzlX3Muo8auIPhsRPb4DqP_DInnWVShOh_I3r4UDt0f2bahAJQjRQsS-Nq8yoJqqMQGY0jIyytfHBDQmw',
 '.issued': 'Thu, 06 Jun 2024 13:11:56 GMT',
 '.expires': 'Thu, 06 Jun 2024 13:26:56 GMT',
 '.refreshexpires': 'Thu, 06 Jun 2024 13:31:56 GMT',
 'expires_at': datetime.datetime(2024, 6, 6, 10, 31, 56, 79097)}

In [60]:
import requests
instrument='Acciones'
url = token.quotes_url.format(instrument=instrument, country='argentina')
headers = {'Authorization': f"Bearer {token.token_info['access_token']}"}
response = requests.get(url=url,headers=headers)
df=pd.DataFrame(response.json()['titulos'])
df=df[['simbolo','ultimoPrecio']]
df.set_index('simbolo',inplace=True)
df

         ultimoPrecio
simbolo
AGRO             57.4
ALUA            965.5
AUSO           3090.0
BBAR           4570.0
BHIP            406.5
...               ...
TGSU2          4665.0
TRAN           1600.0
TXAR            973.0
VALO            308.0
YPFD          27156.0

[77 rows x 1 columns]

In [59]:
import pandas as pd
df=pd.DataFrame(response.json()['titulos'])
df=df[['simbolo','ultimoPrecio']]
df=df.set_index('simbolo',inplace=True)
df

         ultimoPrecio
simbolo
AGRO             57.4
ALUA            965.5
AUSO           3090.0
BBAR           4570.0
BHIP            406.5
...               ...
TGSU2          4665.0
TRAN           1600.0
TXAR            973.0
VALO            308.0
YPFD          27156.0

[77 rows x 1 columns]